---
title: "4. Statistical Reasoning"
subtitle: "Null Hypothesis Testing"
author: "Sharon Klinkenberg & Johnny van Doorn"
date: "10 sep 2024"
footer: "Scientific & Statistical Reasoning"
format:
  revealjs:
    output-ext: slides.html
  html: default
---

## Learning

<iframe style="height:400px;  width:100%;" src="https://www.youtube.com/embed/JC82Il2cjqA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## About SSR

- Book: Discovering Statistics Using JASP
    - For now only available in-browser [here](https://amsuni-my.sharepoint.com/:b:/g/personal/j_b_vandoorn_uva_nl/ESR4n5L9HB5KsKByVbDlsj0BoZLpYD2aWwJstikmEGU25g?e=dKODJR)
        - Individual chapters available [here](https://amsuni-my.sharepoint.com/:f:/g/personal/j_b_vandoorn_uva_nl/EoyhXwuTGZtGvJaobtAr83kBCA-BWxgKN6-kPvKIhKxaEg?e=k0eNPP).
- Software: 
    - JASP - main tool for analyses, data management
    - R - using it as calculator
- Practice: 
    - Tutorials, WA in Ans
    - [Companion website of book](https://johnnydoorn.github.io/discoverjasp/) 
        - Smart Alex tasks
        - Labcoat Leni
        - Self-tests

<!-- Add the required topics below -->

```{r child="../../topics/statistical_reasoning/statistical_reasoning.qmd"}
```

```{r child="../../topics/empirical_cycle/empirical_cycle.qmd"}
```

```{r child="../../topics/physics_experiment/physics_experiment.qmd"}
```


```{r child="../../footer.qmd"}
```

