# Extra: variance and z-scores {.section}

```{r, eval=TRUE, echo=FALSE}
source("../../_setup.R")
```

## Load data {.smaller}

- Anxiety before the exam (EAQ, out of 100)
- Performance: percentage mark

```{r, eval=TRUE, echo=TRUE}
n    <- 10
data <- read.csv(datasetsPath("2026/exam-anxiety.csv"), check.names = FALSE)
data <- data[1:n, c("Exam performance", "Exam anxiety")] # first 10 students
ssrTable(data)
```

## Two different units {.smaller}

```{r, echo = FALSE}
exam_grade <- data$`Exam performance`
anxiety    <- data$`Exam anxiety`
mean.exam  <- mean(exam_grade)
mean.anx   <- mean(anxiety)
N          <- length(exam_grade)

plot(exam_grade,
     bg='orange', pch = 21, bty = "n", ylim = c(0, 100),
     ylab="Variables", las = 1,
     xlab="Student nr.")
points(anxiety, bg='blue', pch = 21)
legend("bottomright", legend = c("Anxiety", "Exam performance (%)"),
       fill = c("blue", "orange"), bty = "n")
lines(rep(mean.exam, N), col='orange')
lines(rep(mean.anx, N), col='blue', lt=1)
```

A deviation of 5 means something different in each.

## Standardize 

$$z = \frac{x_i - \bar{x}}{{sd}_x}$$

```{r, echo=TRUE}
z.exam    <- (exam_grade - mean(exam_grade)) / sd(exam_grade)
z.anxiety <- (anxiety    - mean(anxiety))    / sd(anxiety)
```

___
### Standardize {.smaller}

```{r, echo= FALSE}
mean.z.exam <- mean(z.exam)
mean.z.anx  <- mean(z.anxiety)

plot(z.exam,
     bg  = 'orange', pch = 21, bty = "n", ylim = c(-2.5, 2.5),
     ylab = "z-scores", xlab="Student nr.", las = 1)

points(z.anxiety, pch = 21, bg='blue')
legend("bottomright", legend = c("z-anxiety", "z-exam performance"),
       fill = c("blue", "orange"), bty = "n")

lines(rep(mean.z.exam, N), col='orange')
lines(rep(mean.z.anx, N), col='blue', lt=2)
```

Mean 0, sd 1.

___
### Standardize {.smaller}

```{r, echo= FALSE}
plot(z.exam,
     bg  = 'orange', pch = 21, bty = "n", ylim = c(-2.5, 2.5),
     ylab = "z-scores", xlab="Student nr.", las = 1)

points(z.anxiety, pch = 21, bg='blue')
legend("bottomright", legend = c("z-anxiety", "z-exam performance"),
       fill = c("blue", "orange"), bty = "n")

lines(rep(mean.z.exam, N), col='orange')
lines(rep(mean.z.anx, N), col='blue', lty = 2)

segments(1:N, mean.z.exam, 1:N, z.exam, col='orange')
segments(1:N, mean.z.anx, 1:N, z.anxiety, col='blue', lty = 2)
```
