---
title: "28. Chi-squared test"
subtitle: "Contingency Tables"
author: "Johnny van Doorn"
date: "12 nov 2025"
footer: "Scientific & Statistical Reasoning"
format:
  revealjs:
    output-ext: slide.html
    css: ../../ajohnson.css
  html: default
css: ../../ajohnson.css
---

<div class="goals">
In this lecture we aim to:

<!-- - Stroll down memory lane -->
- Discuss association between categorical variables
  - Contingency tables
- Show this test in JASP
    
<strong>Reading:</strong>
Chapter 16
</div>


```{r child="../../topics/chi_square/chi_square_test.qmd"}
```

# Closing

## Recap

- Chi-square test assesses categorical associations
- Can be used to assess (in)dependence between predictors
- Has test statistic ($\chi^2$) + effect size (odds ratio)
  
## Recommended Exercises

::: {}
- [Exercise 16.1](https://discoverjasp.com/pages/smart_alex#task-16.1),  
[Exercise 16.6](https://discoverjasp.com/pages/smart_alex#task-16.6),
[Exercise 16.7](https://discoverjasp.com/pages/smart_alex#task-16.7)
:::
```{r child="../../footer.qmd"}
```
