{
  "hash": "79f761f2b7129768b2d51fffa4dea337",
  "result": {
    "markdown": "# One-way independent ANOVA {.section}\n\nCompare 2 or more independent groups.\n\n## Assumptions\n\nAssuming th $H_0$ hypothesis to be true, the following should hold:\n\n* Continuous variable\n* Random sample\n* Normally distributed residuals\n    * Q-Q plots (or Shapiro-Wilk)\n* Equal variance within groups (i.e., *Homogeneity of variances*)\n    * Ratio of variances/sd (or Levene's test)\n\n## Jet lag {.smaller}\n\nWright and Czeisler (2002) performed an experiment where they measured the circadian rhythm by the daily cycle of melatonin production in 22 subjects randomly assigned to one of three light treatments.\n\n* Control condition (no light)\n* Knees (3 hour light to back of knees)\n* Eyes (3 hour light in eyes)\n\n\n::: {.cell}\n\n:::\n\n\n## The Data\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-f4e698e1cc65a1c84e74\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f4e698e1cc65a1c84e74\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\"],[0.53,0.36,0.2,-0.37,-0.6,-0.64,-1.27,0.73,0.31,0.03,-0.29,-0.5600000000000001,-0.96,-1.61,-0.78,-0.86,-1.35,-1.48,-1.52,-2.04,-2.83],[\"Control\",\"Control\",\"Control\",\"Control\",\"Control\",\"Control\",\"Control\",\"Knee\",\"Knee\",\"Knee\",\"Knee\",\"Knee\",\"Knee\",\"Knee\",\"Eyes\",\"Eyes\",\"Eyes\",\"Eyes\",\"Eyes\",\"Eyes\",\"Eyes\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>CircadianShift<\\/th>\\n      <th>Condition<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"searching\":false,\"scrollY\":415,\"paging\":false,\"info\":false,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":1},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"CircadianShift\",\"targets\":1},{\"name\":\"Condition\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n\n##\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n## Variance components\n\nVariance | Sum of Squares | DF | Mean Squares | F-ratio\n---------|----------------|----|--------------|---------\nModel    | ${SS}_{model} = \\sum n_k(\\bar{X}_k - \\bar{X})^2$ | $k-1$ | $\\frac{{SS}_{model}}{{df}_{model}}$ | $\\frac{{MS}_{model}}{{MS}_{error}}$\nError    | ${SS}_{error} = \\sum s_k^2 (n_k - 1)$            | $N-k$ | $\\frac{{SS}_{error}}{{df}_{error}}$ | \nTotal    | ${SS}_{total} = {SS}_{model} + {SS}_{error}$     | $N-1$ | $\\frac{{SS}_{total}}{{df}_{total}}$ | \n\nWhere $N$ is the total sample size, $n_k$ is the sample size per category and $k$ is the number of categories. Finally $s_k^2$ is the variance per category.\n\n## Variance questions\n\n- How much total variance is there in the dependent variable?\n  - Variance (total SS) = distance between observations and grand mean\n\n- How much of this variance can we explain by looking at the group means?\n  - Model SS = distance between group means and grand mean\n- How much of this variance is **not** explained by the group means?\n  - Error SS = distance between group means and observations\n\n> DV = Model + Error\n\n## Total variance {.subsection}\n\n$${MS}_{total} = s_x^2$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nms.t <- var(x); ms.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8319357\n```\n:::\n\n```{.r .cell-code}\nsum( (x - mean(x))^2 ) / (length(x) - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8319357\n```\n:::\n:::\n\n\n--------\n\n$${SS}_{total} = s_x^2 (N-1)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- length(x)\n\nss.t <- var(x) * (N-1); ss.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 16.63871\n```\n:::\n\n```{.r .cell-code}\nsum( (x - mean(x))^2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 16.63871\n```\n:::\n:::\n\n\n## Visual ${SS}_{total}$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Model variance\n\n$${MS}_{model} = \\frac{{SS}_{model}}{{df}_{model}} \\\\ {df}_{model} = k - 1$$\n\nWhere $k$ is the number of independent groups and\n\n$${SS}_{model} = \\sum_{k} n_k (\\bar{X}_k - \\bar{X})^2$$\n\n\n::: {.cell}\n\n:::\n\n\n--------\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.380886\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.690443\n```\n:::\n:::\n\n\n## Visual ${SS}_{model}$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## Error variance {.smaller}\n\n$${MS}_{error} = \\frac{{SS}_{error}}{{df}_{error}} \\\\ {df}_{error} = N - k$$\n\nwhere\n\n$${SS}_{error} = \\sum_{k} s_k^2 (n_k - 1) = \\sum_{k} \\frac{\\sum (x_{ik} - \\bar{x}_k)^2}{(n_k - 1)} (n_k - 1)$$\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9.257829\n```\n:::\n:::\n\n\n-----\n\n$${MS}_{error} = \\frac{{SS}_{error}}{{df}_{error}} \\\\ {df}_{error} = N - k$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.e <- (N - k)\nms.e <- ss.e / df.e; ms.e\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5143238\n```\n:::\n:::\n\n\n## Visual ${SS}_{error}$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n## Variance components {.subsection}\n\n$${SS}_{total} = {SS}_{model} + {SS}_{error}$$\n$$16.6387143 = 7.3808857 + 9.2578286$$\n\n$${MS}_{total} = \\frac{{SS}_{total}}{{df}_{total}}= 0.8319357$$\n$${MS}_{model} = \\frac{{SS}_{model}}{{df}_{model}}= 3.6904429$$\n$${MS}_{error} = \\frac{{SS}_{error}}{{df}_{error}} = 0.5143238$$\n\n## F-ratio {.subsection}\n\n$$F = \\frac{{MS}_{model}}{{MS}_{error}} = \\frac{{SIGNAL}}{{NOISE}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfStat <- ms.m / ms.e; fStat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.17533\n```\n:::\n:::\n\n\n## Reject $H_0$?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n## Contrasts\n\nPlanned comparisons\n\n* Exploring differences of theoretical interest\n* Higher precision\n* Higher power\n\n## Contrasts\n\n* Values add up to 0\n\n<img src=\"../../topics/ANOVA_one_way_independent/pie2.png\" style=\"height:200px;\" >\n<img src=\"../../topics/ANOVA_one_way_independent/pie1.png\" style=\"height:200px;\" >\n\n##\n\n<img src=\"../../topics/ANOVA_one_way_independent/pie3.png\" style=\"height:200px;\" >\n\n* AB-CDEF &rarr; A-B &rarr; CD-EF &rarr; C-D &rarr; E-F\n* A-BCDEF &rarr; A-B &rarr; A-C\n* A-BCDEG &rarr; BC-DEF &rarr; B-C &rarr; B-DEF\n* ABC-DEF &rarr; BC-DEF &rarr; B-C\n\n##\n\nAssign values that sum to 0. Same values define chunk.\n\n* AB-CDEF &rarr; A-B &rarr; CD-EF &rarr; C-D &rarr; E-F\n\n|            |A|B|C|D|E|F\n|------------|-|-|-|-|-|-\n| Contrast 1 | | | | | |\n| Contrast 2 | | | | | |\n| Contrast 3 | | | | | |\n| Contrast 4 | | | | | |\n\n##\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Post-hoc\n\nUnplanned comparisons\n\n* Exploring all possible differences\n* Adjust T value for inflated type 1 error\n    * [Why?](https://xkcd.com/882/)\n    * Different procedures exist (e.g., Tukey, Bonferroni)\n* Same procedure as contrasts, but: **exploratory vs. confirmatory research**\n\n\n## Effect size $\\eta^2$\n\nThe amount of explained variance $R^2$ as a general effect size measure.\n\n$$R^2 = \\frac{{SS}_{model}}{{SS}_{total}} = \\eta^2$$\nTaking the square root gives us Cohen's $r$.\n\n## Effect size $\\omega^2$\n\nLess biased towards just the sample is omega squared $\\omega^2$.\n\n$$\\omega^2 = \\frac{{SS}_{model} - ({df}_{model}){MS}_{error}}{{SS}_{total}+{MS}_{error}}$$\nBut what does it say?\n\n## Effect size $d$\n\nA more interpretable effect size measure is $d_{Contrast}$. Which gives Cohen's $d$ for a specific contrast.\n\n$$d_{Contrast} = \\sqrt{\\frac{2t}{\\sqrt{n_1 + n_2}}}$$",
    "supporting": [
      "ANOVA_one_way_independent_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"ANOVA_one_way_independent_files/libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"ANOVA_one_way_independent_files/libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"ANOVA_one_way_independent_files/libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"ANOVA_one_way_independent_files/libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"ANOVA_one_way_independent_files/libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"ANOVA_one_way_independent_files/libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"ANOVA_one_way_independent_files/libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"ANOVA_one_way_independent_files/libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"ANOVA_one_way_independent_files/libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"ANOVA_one_way_independent_files/libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}