{
  "hash": "7c0cd904f725c3c661be8291917af5a9",
  "result": {
    "markdown": "# One-way independent ANOVA {.section}\n\nCompare 2 or more independent groups.\n\n## Assumptions\n\nAssuming th $H_0$ hypothesis to be true, the following should hold:\n\n* Continuous variable\n* Random sample\n* Normally distributed\n    * Shapiro-Wilk test or Q-Q plots\n* Equal variance within groups\n    * Levene's test\n\n## Jet lag {.smaller}\n\nWright and Czeisler (2002) performed an experiment where they measured the circadian rhythm by the daily cycle of melatonin production in 22 subjects randomly assigned to one of three light treatments.\n\n* Control condition (no light)\n* Knees (3 hour light to back of knees)\n* Eyes (3 hour light in eyes)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())\nx.c <- c( .53, .36,  .2,  -.37, -.6,  -.64, -1.27) # Control \nx.k <- c( .73, .31,  .03, -.29, -.56, -.96, -1.61) # Knees\nx.e <- c(-.78,-.86,-1.35,-1.48,-1.52,-2.04, -2.83) # Eyes\nx   <- c( x.c, x.k, x.e )                          # Conditions combined\n```\n:::\n\n\n##\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n## Variance components\n\nVariance | Sum of Squares | DF | Mean Squares | F-ratio\n---------|----------------|----|--------------|---------\nModel    | ${SS}_{model} = \\sum n_k(\\bar{X}_k - \\bar{X})^2$ | $k-1$ | $\\frac{{SS}_{model}}{{df}_{model}}$ | $\\frac{{MS}_{model}}{{MS}_{error}}$\nError    | ${SS}_{error} = \\sum s_k^2 (n_k - 1)$            | $N-k$ | $\\frac{{SS}_{error}}{{df}_{error}}$ | \nTotal    | ${SS}_{total} = {SS}_{model} + {SS}_{error}$     | $N-1$ | $\\frac{{SS}_{total}}{{df}_{total}}$ | \n\nWhere $N$ is the total sample size, $n_k$ is the sample size per category and $k$ is the number of categories. Finally $s_k^2$ is the variance per category.\n\n## Total variance {.subsection}\n\n$${MS}_{total} = s_x^2$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nms.t <- var(x); ms.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8319357\n```\n:::\n\n```{.r .cell-code}\nsum( (x - mean(x))^2 ) / (length(x) - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8319357\n```\n:::\n:::\n\n\n--------\n\n$${SS}_{total} = s_x^2 (N-1)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- length(x)\n\nss.t <- var(x) * (N-1); ss.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 16.63871\n```\n:::\n\n```{.r .cell-code}\nsum( (x - mean(x))^2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 16.63871\n```\n:::\n:::\n\n\n## Visual ${SS}_{total}$\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\n# Assign labels\nlab <- c(\"Control\", \"Knee\", \"Eyes\") \n\n# Plot all data points\nplot(1:N,x, \n     ylab=\"Shift in circadian rhythm (h)\",\n     xlab=\"Light treatment\",\n     main=\"Total variance\")\n\n# Add mean line\nlines(c(1,22),rep(mean(x),2),lwd=3)\n\n# Add delta lines / variance components\nsegments(1:N, mean(x), 1:N, x)\n\n# Add labels\ntext(c(4,11.5,18.5),rep(.6,3),labels=lab)\n```\n\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n## Model variance\n\n$${MS}_{model} = \\frac{{SS}_{model}}{{df}_{model}} \\\\ {df}_{model} = k - 1$$\n\nWhere $k$ is the number of independent groups and\n\n$${SS}_{model} = \\sum_{k} n_k (\\bar{X}_k - \\bar{X})^2$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk   <- 3\nn.c <- length(x.c)\nn.k <- length(x.k)\nn.e <- length(x.e)\n```\n:::\n\n\n--------\n\n\n::: {.cell}\n\n```{.r .cell-code}\nss.m.c <- n.c * (mean(x.c) - mean(x))^2\nss.m.k <- n.k * (mean(x.k) - mean(x))^2\nss.m.e <- n.e * (mean(x.e) - mean(x))^2\n\nss.m <- sum(ss.m.c, ss.m.k, ss.m.e); ss.m\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.380886\n```\n:::\n\n```{.r .cell-code}\ndf.m <- (k - 1)\nms.m <- ss.m / df.m; ms.m\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.690443\n```\n:::\n:::\n\n\n## Visual ${SS}_{model}$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Error variance {.smaller}\n\n$${MS}_{error} = \\frac{{SS}_{error}}{{df}_{error}} \\\\ {df}_{error} = N - k$$\n\nwhere\n\n$${SS}_{error} = \\sum_{k} s_k^2 (n_k - 1) = \\sum_{k} \\frac{\\sum (x_{ik} - \\bar{x}_k)^2}{(n_k - 1)} (n_k - 1)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nss.e.c <- var(x.c) * (n.c - 1)\nss.e.k <- var(x.k) * (n.k - 1)\nss.e.e <- var(x.e) * (n.e - 1)\nss.e   <- sum(ss.e.c, ss.e.k, ss.e.e); ss.e\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9.257829\n```\n:::\n:::\n\n\n-----\n\n$${MS}_{error} = \\frac{{SS}_{error}}{{df}_{error}} \\\\ {df}_{error} = N - k$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.e <- (N - k)\nms.e <- ss.e / df.e; ms.e\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5143238\n```\n:::\n:::\n\n\n## Visual ${SS}_{error}$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n## Variance components {.subsection}\n\n$${SS}_{total} = {SS}_{model} + {SS}_{error}$$\n$$16.6387143 = 7.3808857 + 9.2578286$$\n\n$${MS}_{total} = \\frac{{SS}_{total}}{{df}_{total}}= 0.8319357$$\n$${MS}_{model} = \\frac{{SS}_{model}}{{df}_{model}}= 3.6904429$$\n$${MS}_{error} = \\frac{{SS}_{error}}{{df}_{error}} = 0.5143238$$\n\n## F-ratio {.subsection}\n\n$$F = \\frac{{MS}_{model}}{{MS}_{error}} = \\frac{{SIGNAL}}{{NOISE}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfStat <- ms.m / ms.e; fStat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.17533\n```\n:::\n:::\n\n\n## Reject $H_0$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif(!\"visualize\" %in% installed.packages()) { install.packages(\"visualize\") }\nlibrary(\"visualize\")\n\nvisualize.f(fStat, df.m,df.e,section=\"upper\")\n```\n\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n## Contrasts\n\nPlanned comparisons\n\n* Exploring differences of theoretical interest\n* Higher precision\n* Higher power\n\n## Contrasts\n\n* Values add up to 0\n\n<img src=\"../../topics/ANOVA_one_way_independent/pie2.png\" style=\"height:200px;\" >\n<img src=\"../../topics/ANOVA_one_way_independent/pie1.png\" style=\"height:200px;\" >\n\n##\n\n<img src=\"../../topics/ANOVA_one_way_independent/pie3.png\" style=\"height:200px;\" >\n\n* AB-CDEF &rarr; A-B &rarr; CD-EF &rarr; C-D &rarr; E-F\n* A-BCDEF &rarr; A-B &rarr; A-C\n* A-BCDEG &rarr; BC-DEF &rarr; B-C &rarr; B-DEF\n* ABC-DEF &rarr; BC-DEF &rarr; B-C\n\n##\n\nAssign values that sum to 0. Same values define chunk.\n\n* AB-CDEF &rarr; A-B &rarr; CD-EF &rarr; C-D &rarr; E-F\n\n|            |A|B|C|D|E|F\n|------------|-|-|-|-|-|-\n| Contrast 1 | | | | | |\n| Contrast 2 | | | | | |\n| Contrast 3 | | | | | |\n| Contrast 4 | | | | | |\n\n##\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ANOVA_one_way_independent_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n## Post-hoc\n\nUnplanned comparisons\n\n* Exploring all possible differences\n* Adjust T value for inflated type 1 error\n    * [Why?](https://xkcd.com/882/)\n    * Different procedures exist (e.g., Tukey, Bonferroni)\n* Same procedure as contrasts, but: **exploratory vs. confirmatory research**\n\n\n## Effect size $\\eta^2$\n\nThe amount of explained variance $R^2$ as a general effect size measure.\n\n$$R^2 = \\frac{{SS}_{model}}{{SS}_{total}} = \\eta^2$$\nTaking the square root gives us Cohen's $r$.\n\n## Effect size $\\omega^2$\n\nLess biased towards just the sample is omega squared $\\omega^2$.\n\n$$\\omega^2 = \\frac{{SS}_{model} - ({df}_{model}){MS}_{error}}{{SS}_{total}+{MS}_{error}}$$\nBut what does it say?\n\n## Effect size $d$\n\nA more interpretable effect size measure is $d_{Contrast}$. Which gives Cohen's $d$ for a specific contrast.\n\n$$d_{Contrast} = \\sqrt{\\frac{2t}{\\sqrt{n_1 + n_2}}}$$",
    "supporting": [
      "ANOVA_one_way_independent_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}