{
  "hash": "c740a02b47cd62fe2b488a06ba35b70e",
  "result": {
    "markdown": "---\ntitle    : \"11. ANOVA\"\nsubtitle : \"F-distribution & One-way independent ANOVA\"\nauthor: \"Sharon Kinkenberg & Johnny van Doorn\"\ndate     : \"01 oct 2024\"\nfooter: \"Scientific & Statistical Reasoning\"\nformat: \n  html: default\n  revealjs: \n    output-ext: slide.html\n---\n\n\n## Block 2\n- More complex analyses\n    - All sorts of ANOVA's (Ch11-14)\n    - Nonparametrics (Ch15)\n    - $\\chi^2$ (Contingency tables; Ch16)\n\n\n## Today\n- Introducing ANOVA\n- F-Distribution\n- ANOVA in JASP\n\n\n## Models {.center}\n\n<div style=\"font-size:200%; transform: rotate(-11deg);\">\n$$\\text{outcome} = \\text{model} + \\text{error}$$\n</div>\n\n\n\n# One-way independent ANOVA {.section}\n\nCompare 2 or more independent groups.\n\n## Assumptions\n\nAssuming th $H_0$ hypothesis to be true, the following should hold:\n\n* Continuous variable\n* Random sample\n* Normally distributed\n    * Shapiro-Wilk test or Q-Q plots\n* Equal variance within groups (i.e., *Homogeneity of variances*)\n    * Levene's test or ratio of variances\n\n## Jet lag {.smaller}\n\nWright and Czeisler (2002) performed an experiment where they measured the circadian rhythm by the daily cycle of melatonin production in 22 subjects randomly assigned to one of three light treatments.\n\n* Control condition (no light)\n* Knees (3 hour light to back of knees)\n* Eyes (3 hour light in eyes)\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())\nx.c <- c( .53, .36,  .2,  -.37, -.6,  -.64, -1.27) # Control \nx.k <- c( .73, .31,  .03, -.29, -.56, -.96, -1.61) # Knees\nx.e <- c(-.78,-.86,-1.35,-1.48,-1.52,-2.04, -2.83) # Eyes\nx   <- c( x.c, x.k, x.e )                          # Conditions combined\n```\n:::\n\n##\n\n::: {.cell}\n::: {.cell-output-display}\n![](11.-f_distribution_ANOVA_one_way_independent_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n## Variance components\n\nVariance | Sum of Squares | DF | Mean Squares | F-ratio\n---------|----------------|----|--------------|---------\nModel    | ${SS}_{model} = \\sum n_k(\\bar{X}_k - \\bar{X})^2$ | $k-1$ | $\\frac{{SS}_{model}}{{df}_{model}}$ | $\\frac{{MS}_{model}}{{MS}_{error}}$\nError    | ${SS}_{error} = \\sum s_k^2 (n_k - 1)$            | $N-k$ | $\\frac{{SS}_{error}}{{df}_{error}}$ | \nTotal    | ${SS}_{total} = {SS}_{model} + {SS}_{error}$     | $N-1$ | $\\frac{{SS}_{total}}{{df}_{total}}$ | \n\nWhere $N$ is the total sample size, $n_k$ is the sample size per category and $k$ is the number of categories. Finally $s_k^2$ is the variance per category.\n\n## Total variance {.subsection}\n\n$${MS}_{total} = s_x^2$$\n\n::: {.cell}\n\n```{.r .cell-code}\nms.t <- var(x); ms.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8319357\n```\n:::\n\n```{.r .cell-code}\nsum( (x - mean(x))^2 ) / (length(x) - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8319357\n```\n:::\n:::\n\n--------\n\n$${SS}_{total} = s_x^2 (N-1)$$\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- length(x)\n\nss.t <- var(x) * (N-1); ss.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 16.63871\n```\n:::\n\n```{.r .cell-code}\nsum( (x - mean(x))^2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 16.63871\n```\n:::\n:::\n\n## Visual ${SS}_{total}$\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\n# Assign labels\nlab <- c(\"Control\", \"Knee\", \"Eyes\") \n\n# Plot all data points\nplot(1:N,x, \n     ylab=\"Shift in circadian rhythm (h)\",\n     xlab=\"Light treatment\",\n     main=\"Total variance\")\n\n# Add mean line\nlines(c(1,22),rep(mean(x),2),lwd=3)\n\n# Add delta lines / variance components\nsegments(1:N, mean(x), 1:N, x)\n\n# Add labels\ntext(c(4,11.5,18.5),rep(.6,3),labels=lab)\n```\n\n::: {.cell-output-display}\n![](11.-f_distribution_ANOVA_one_way_independent_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n## Model variance\n\n$${MS}_{model} = \\frac{{SS}_{model}}{{df}_{model}} \\\\ {df}_{model} = k - 1$$\n\nWhere $k$ is the number of independent groups and\n\n$${SS}_{model} = \\sum_{k} n_k (\\bar{X}_k - \\bar{X})^2$$\n\n::: {.cell}\n\n```{.r .cell-code}\nk   <- 3\nn.c <- length(x.c)\nn.k <- length(x.k)\nn.e <- length(x.e)\n```\n:::\n\n--------\n\n::: {.cell}\n\n```{.r .cell-code}\nss.m.c <- n.c * (mean(x.c) - mean(x))^2\nss.m.k <- n.k * (mean(x.k) - mean(x))^2\nss.m.e <- n.e * (mean(x.e) - mean(x))^2\n\nss.m <- sum(ss.m.c, ss.m.k, ss.m.e); ss.m\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.380886\n```\n:::\n\n```{.r .cell-code}\ndf.m <- (k - 1)\nms.m <- ss.m / df.m; ms.m\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.690443\n```\n:::\n:::\n\n## Visual ${SS}_{model}$\n\n::: {.cell}\n::: {.cell-output-display}\n![](11.-f_distribution_ANOVA_one_way_independent_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n## Error variance {.smaller}\n\n$${MS}_{error} = \\frac{{SS}_{error}}{{df}_{error}} \\\\ {df}_{error} = N - k$$\n\nwhere\n\n$${SS}_{error} = \\sum_{k} s_k^2 (n_k - 1) = \\sum_{k} \\frac{\\sum (x_{ik} - \\bar{x}_k)^2}{(n_k - 1)} (n_k - 1)$$\n\n::: {.cell}\n\n```{.r .cell-code}\nss.e.c <- var(x.c) * (n.c - 1)\nss.e.k <- var(x.k) * (n.k - 1)\nss.e.e <- var(x.e) * (n.e - 1)\nss.e   <- sum(ss.e.c, ss.e.k, ss.e.e); ss.e\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9.257829\n```\n:::\n:::\n\n-----\n\n$${MS}_{error} = \\frac{{SS}_{error}}{{df}_{error}} \\\\ {df}_{error} = N - k$$\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.e <- (N - k)\nms.e <- ss.e / df.e; ms.e\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5143238\n```\n:::\n:::\n\n## Visual ${SS}_{error}$\n\n::: {.cell}\n::: {.cell-output-display}\n![](11.-f_distribution_ANOVA_one_way_independent_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n## Variance components {.subsection}\n\n$${SS}_{total} = {SS}_{model} + {SS}_{error}$$\n$$16.6387143 = 7.3808857 + 9.2578286$$\n\n$${MS}_{total} = \\frac{{SS}_{total}}{{df}_{total}}= 0.8319357$$\n$${MS}_{model} = \\frac{{SS}_{model}}{{df}_{model}}= 3.6904429$$\n$${MS}_{error} = \\frac{{SS}_{error}}{{df}_{error}} = 0.5143238$$\n\n## F-ratio {.subsection}\n\n$$F = \\frac{{MS}_{model}}{{MS}_{error}} = \\frac{{SIGNAL}}{{NOISE}}$$\n\n::: {.cell}\n\n```{.r .cell-code}\nfStat <- ms.m / ms.e; fStat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.17533\n```\n:::\n:::\n\n## Reject $H_0$?\n\n::: {.cell}\n::: {.cell-output-display}\n![](11.-f_distribution_ANOVA_one_way_independent_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n## Contrasts\n\nPlanned comparisons\n\n* Exploring differences of theoretical interest\n* Higher precision\n* Higher power\n\n## Contrasts\n\n* Values add up to 0\n\n<img src=\"../../topics/ANOVA_one_way_independent/pie2.png\" style=\"height:200px;\" >\n<img src=\"../../topics/ANOVA_one_way_independent/pie1.png\" style=\"height:200px;\" >\n\n##\n\n<img src=\"../../topics/ANOVA_one_way_independent/pie3.png\" style=\"height:200px;\" >\n\n* AB-CDEF &rarr; A-B &rarr; CD-EF &rarr; C-D &rarr; E-F\n* A-BCDEF &rarr; A-B &rarr; A-C\n* A-BCDEG &rarr; BC-DEF &rarr; B-C &rarr; B-DEF\n* ABC-DEF &rarr; BC-DEF &rarr; B-C\n\n##\n\nAssign values that sum to 0. Same values define chunk.\n\n* AB-CDEF &rarr; A-B &rarr; CD-EF &rarr; C-D &rarr; E-F\n\n|            |A|B|C|D|E|F\n|------------|-|-|-|-|-|-\n| Contrast 1 | | | | | |\n| Contrast 2 | | | | | |\n| Contrast 3 | | | | | |\n| Contrast 4 | | | | | |\n\n##\n\n::: {.cell}\n::: {.cell-output-display}\n![](11.-f_distribution_ANOVA_one_way_independent_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n## Post-hoc\n\nUnplanned comparisons\n\n* Exploring all possible differences\n* Adjust T value for inflated type 1 error\n    * [Why?](https://xkcd.com/882/)\n    * Different procedures exist (e.g., Tukey, Bonferroni)\n* Same procedure as contrasts, but: **exploratory vs. confirmatory research**\n\n\n## Effect size $\\eta^2$\n\nThe amount of explained variance $R^2$ as a general effect size measure.\n\n$$R^2 = \\frac{{SS}_{model}}{{SS}_{total}} = \\eta^2$$\nTaking the square root gives us Cohen's $r$.\n\n## Effect size $\\omega^2$\n\nLess biased towards just the sample is omega squared $\\omega^2$.\n\n$$\\omega^2 = \\frac{{SS}_{model} - ({df}_{model}){MS}_{error}}{{SS}_{total}+{MS}_{error}}$$\nBut what does it say?\n\n## Effect size $d$\n\nA more interpretable effect size measure is $d_{Contrast}$. Which gives Cohen's $d$ for a specific contrast.\n\n$$d_{Contrast} = \\sqrt{\\frac{2t}{\\sqrt{n_1 + n_2}}}$$\n\n\n# F-distribution {.section}\n\n## Ronald Fisher {.smaller .subsection}\n\n::: {.columns}\n\n::: {.column width=\"70%\"}\n\nThe F-distribution, also known as Snedecor's F distribution or the Fisher--Snedecor distribution (after Ronald Fisher and George W. Snedecor) is, in probability theory and statistics, a continuous probability distribution. The F-distribution arises frequently as the null distribution of a test statistic, most notably in the analysis of variance; see F-test.\n\n[Wikipedia](https://en.wikipedia.org/wiki/F-distribution)\n\nSir Ronald Aylmer Fisher FRS (17 February 1890 -- 29 July 1962), known as R.A. Fisher, was an English statistician, evolutionary biologist, mathematician, geneticist, and eugenicist. Fisher is known as one of the three principal founders of population genetics, creating a mathematical and statistical basis for biology and uniting natural selection with Mendelian genetics.\n\n[Wikipedia](https://en.wikipedia.org/wiki/Ronald_Fisher)\n\n:::\n\n::: {.column width=\"30%\"}\n\n![Ronald Fisher](https://upload.wikimedia.org/wikipedia/commons/a/aa/Youngronaldfisher2.JPG){width=\"291\"}\n\n:::\n\n:::\n\n## Analysing variance\n\n[Decomposing variance example of height for males and females (video from last year's lecture).](https://webcolleges.uva.nl/Mediasite/Play/42718d5968df45b29c089fcd02bcb86a1d?playFrom=377000)\n\n## Population distribution {.smaller .subsection}\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nlayout(matrix(c(2:6,1,1,7:8,1,1,9:13), 4, 4))\n\nn  <- 56    # Sample size\ndf <- n - 1 # Degrees of freedom\n\nmu    <- 120\nsigma <- 15\n\nIQ <- seq(mu-45, mu+45, 1)\n\npar(mar = c(4,2,0,0))  \nplot(IQ, dnorm(IQ, mean = mu, sd = sigma), type='l', col=\"red\")\n\nn.samples = 12\n\nfor(i in 1:n.samples) {\n  \n  par(mar = c(2,2,0,0))  \n  hist(rnorm(n, mu, sigma), main=\"\", cex.axis=.5, col=\"red\")\n  \n}\n```\n\n::: {.cell-output-display}\n![](11.-f_distribution_ANOVA_one_way_independent_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n## F-statistic\n\n$$F = \\frac{{MS}_{model}}{{MS}_{error}} = \\frac{{SIGNAL}}{{NOISE}}$$\n\nSo the $F$-statistic represents a signal to noise ratio by deviding the model variance component by the error variance component.\n\n## A samples\n\nLet's take two sample from our normal populatiion and calculate the F-value.\n\n::: {.cell}\n\n```{.r .cell-code}\nx.1 <- rnorm(n, mu, sigma)\nx.2 <- rnorm(n, mu, sigma)\n\ndata <- data.frame(group = rep(c(\"s1\", \"s2\"), each=n), score = c(x.1,x.2))\n\t\nfStat <- summary(aov(lm(score ~ group, data)))[[1]]$F[1]\nfStat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3441866\n```\n:::\n:::\n\n## More samples {.smaller .subsection}\n\nlet's take more samples and calculate the F-value every time.\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nnSamples <- 1000\n\nfValues = vector()\n\nfor(i in 1:nSamples) {\n  \n  x1 <- rnorm(n, mu, sigma); x1\n  x2 <- rnorm(n, mu, sigma); x2\n\n  data <- data.frame(group = rep(c(\"s1\", \"s2\"), each=n), score = c(x1,x2))\n\t\n  fValues[i] <- summary(aov(lm(score ~ group, data)))[[1]]$F[1]\n\n}\n\nk = 2\nN = 2*n\n\ndfModel = k - 1\ndfError = N - k\n\nhist(fValues, freq = FALSE, main=\"F-values\", breaks=100)\nfVal = seq(0, 6, .01)\nlines(fVal, df(fVal,dfModel, dfError), col = \"red\")\n```\n\n::: {.cell-output-display}\n![](11.-f_distribution_ANOVA_one_way_independent_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n## F-distribution {.smaller}\n\nSo if the population is normaly distributed (assumption of normality) the f-distribution represents the signal to noise ration given a certain number of samples (${df}_{model} = k - 1$) and sample size (${df}_{error} = N - k$).\n\nThe F-distibution therefore is different for different sample sizes and number of groups.\n\n## F-distribution {.smaller}\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nmultiple.n  = c(5, 15, 30)\nmultiple.k  = c(2, 4, 6)\nmultiple.df.model = multiple.k - 1\nmultiple.df.error = multiple.n - multiple.k\ncol         = rainbow(length(multiple.df.model) * length(multiple.df.error))\nfVals = seq(0, 10, .01)\n\nplot(fVals,  df(fVals, multiple.df.model[1], multiple.df.error[1]), type = \"l\", \n     xlim = c(0,10), ylim = c(0,.85), \n     xlab = \"F\", ylab=\"density\", \n     col  = col[1], main=\"F-distributions\" )\n\ndfs = expand.grid(multiple.df.model, multiple.df.error)\n\nfor(i in 2:dim(dfs)[1]) { \n  \n  lines(fVals, df(fVals, dfs[i,1], dfs[i,2]), col=col[i])\n  \n  critical.f <- qf(.95, dfs[i,1], dfs[i,2])\n  \n  f.alpha <- seq(critical.f, 1000, .01)\n  \n  polygon(c(f.alpha, rev(f.alpha)), c(df(f.alpha, dfs[i,1], dfs[i,2]), f.alpha*0 ), col= rgb(1,.66,0, .5), border = col[i])\n  \n  lines(c(critical.f+.1, 5), c(.02, .2), col=col[i])\n        \n}\n\ntext(5,.2, expression(paste(alpha, \"= 5%\")), pos =3)\n\nlegend(\"topright\", legend = paste(\"df model =\",dfs[,1], \"df error =\", dfs[,2]), lty=1, col = col, cex=.75)\n```\n\n::: {.cell-output-display}\n![](11.-f_distribution_ANOVA_one_way_independent_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n## F-distribution {.flexbox .vcenter}\n\n![Animated F-distrigutions](../../topics/f_distribution/f_distributions.gif)\n\n\n<!-- Footer insert below -->\n\n\n\n# End\n\n## Contact\n\n<script src=\"https://use.fontawesome.com/23c1d38eea.js\"></script>\n\n<ul class=\"fa-ul\" style=\"color:black; list-style:none;\">\n<li><i class=\"fa-li fa fa-envelope-o\"></i> <a style=\"unicode-bidi:bidi-override; direction: rtl; color:black\" href=\"javascript:window.location.href = 'mailto:' + ['j.b.vandoorn','uva.nl'].join('@')\">ln.AvU@nrooDnav.B.J</a></li>\n<li><i class=\"fa-li fa fa-github\"></i> <a href=\"https://github.com/JohnnyDoorn\" target=\"_blank\" style=\"color:black; border-bottom:none;\">JohnnyDoorn</a></li>\n</ul>\n\n<small style=\"text-align:left;\">\n\n\n[![CC BY-NC-SA 4.0][cc-by-nc-sa-image]][cc-by-nc-sa]\n\n[cc-by-nc-sa]: http://creativecommons.org/licenses/by-nc-sa/4.0/\n[cc-by-nc-sa-image]: https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png\n[cc-by-nc-sa-shield]: https://img.shields.io/badge/License-CC%20BY--NC--SA%204.0-lightgrey.svg\n\n</small>\n",
    "supporting": [
      "11.-f_distribution_ANOVA_one_way_independent_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}