<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="JvD">
<meta name="dcterms.date" content="2023-11-03">

<title>Why include an intercept in linear regression?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="IncludingIntercept_files/libs/clipboard/clipboard.min.js"></script>
<script src="IncludingIntercept_files/libs/quarto-html/quarto.js"></script>
<script src="IncludingIntercept_files/libs/quarto-html/popper.min.js"></script>
<script src="IncludingIntercept_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="IncludingIntercept_files/libs/quarto-html/anchor.min.js"></script>
<link href="IncludingIntercept_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="IncludingIntercept_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="IncludingIntercept_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="IncludingIntercept_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="IncludingIntercept_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#take-aways" id="toc-take-aways" class="nav-link active" data-scroll-target="#take-aways">Take-aways</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="IncludingIntercept.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Why include an intercept in linear regression?</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">JvD </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Amsterdam
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 3, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"JASP_Files/Album Sales.csv"</span>) <span class="co"># Load data </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data) <span class="co"># inspect first 5 rows of the data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   adverts sales airplay attract
1   10.256   330      43      10
2  985.685   120      28       7
3 1445.563   360      35       7
4 1188.193   270      33       7
5  574.513   220      44       5
6  568.954   170      19       5</code></pre>
</div>
</div>
<p>In linear regression, we calculate regression coefficients, which we use to predict the data. The difference between prediction and observation then informs us of the accuracy of the model. The interpretation of the various metrics (e.g., <span class="math inline">\(t\)</span>-statistic for the regression coefficients, <span class="math inline">\(F\)</span>-statistic for the overall model accuracy) depends on various assumptions of the linear model. A core assumption here is that there is no systematic error: our model should be equally accurate/wrong across the whole range of its predictions</p>
<p>We can fit a regression model with one predictor (airplay), and include the intercept (done by default)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mainModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> airplay, <span class="at">data =</span> data)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>mainModel<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     airplay 
  84.872508    3.939182 </code></pre>
</div>
</div>
<p>But, we can also choose to omit the intercept, and only estimate a single <span class="math inline">\(b\)</span> (for airplay):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>omitInterceptModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> airplay, <span class="at">data =</span> data)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>omitInterceptModel<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>airplay 
6.51522 </code></pre>
</div>
</div>
<!-- ```{r, fig.align='center', echo=FALSE} -->
<!-- par(mfrow = c(1, 2)) -->
<!-- r <- cor(mainModel$fitted.values, data$sales) -->
<!-- r.2 <- round(r^2, 2) -->
<!-- r <- round(r, 2) -->
<!-- plot( mainModel$fitted.values, data$sales, las = 1, ylab = "Outcome", xlab = "Model Prediction", main =  bquote("r ="~ .(r) ~ "," ~ r^2 ~ " = " ~ .(r.2)),  -->
<!--       ylim=c(0,400), xlim=c(0, 400), pch = 21, bg = "turquoise", bty = "n") -->
<!-- abline(lm(data$sales ~ mainModel$fitted.values), lwd = 3, col = "purple") -->
<!-- r <- cor(omitInterceptModel$fitted.values, data$sales) -->
<!-- r.2 <- round(r^2, 2) -->
<!-- r <- round(r, 2) -->
<!-- plot(omitInterceptModel$fitted.values, data$sales, las = 1, ylab = "Outcome", xlab = "Model Prediction", main =  bquote("r ="~ .(r) ~ "," ~ r^2 ~ " = " ~ .(r.2)),  -->
<!--      ylim=c(0,400), xlim=c(0, 400), pch = 21, bg = "turquoise", bty = "n") -->
<!-- abline(lm(data$sales ~ omitInterceptModel$fitted.values), lwd = 3, col = "purple") -->
<!-- ``` -->
<p>For both models, their regression coefficients dictate what they predict:</p>
<p><span class="math inline">\({\text{model prediction with intercept}} = 84.87 + 3.94 \times \text{airplay}\)</span></p>
<p><span class="math inline">\({\text{model prediction without intercept}} = 6.52 \times \text{airplay}\)</span></p>
<p>We can plot sales and airplay, and add the regression lines for both models (the lines show what each model predicts). The slopes of these lines are dictated by the <span class="math inline">\(b_1\)</span> weights, while the overall height of the lines is dictated by the <span class="math inline">\(b_0\)</span> weights. For the model without an intercept, <span class="math inline">\(b_0\)</span> is set to 0, while in the intercept model <span class="math inline">\(b_0\)</span> is allowed to be different from 0. You can see this in the plot below, where the purple line crosses the y-axis at <span class="math inline">\(84.87\)</span> (i.e., for 0 airplay, it predicts <span class="math inline">\(84.87\)</span> sales), while the orange line crosses the y-axis at 0 (i.e., for 0 airplay, it predicts 0 sales).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="IncludingIntercept_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From this plot, it seems that the model without intercept is still doing a good job of capturing the data. The regression line even has a steeper slope for this model compared to the main model. If we would look at the associated t- and p-values for the regression coefficient of airplay, they would be even more extreme for the model without the intercept. That’s good right?</p>
<p>Well, the linear model that we use to assess the effects of the predictor variable has various assumptions. One of the most important assumptions is that there is no systematic error in the model (i.e., <a href="https://en.wikipedia.org/wiki/Homoscedasticity_and_heteroscedasticity">homoscedasiticity of error</a>). In other words, our model should be equally accurate/wrong across the whole range of its predictions. To assess this assumption, we can look at a scatterplot of the standardized (i.e., z-scores) model predictions and residuals, and hope to see an uncorrelated cloud of points, rather than some other shape (e.g., funnel shape).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="IncludingIntercept_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that while the residuals on the left seem uncorrelated with the predicted values (correlation residual vs.&nbsp;prediction = 0), there is some systematic error going on in the model without intercept (correlation residual vs.&nbsp;prediction = -0.439).<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>By omitting the intercept, we have introduced systematic error into our model: because the regression line needs to start at 0 (instead of 85), it will systematically <em>underestimate</em> low album sales, while it will systematically <em>overestimate</em> high album sales. The systematic error due to ignoring the intercept endangers the interpretation of the other regression coefficients: we will either under- or overestimate their influence.</p>
<p>The systematic error introduced by omitting the intercept is also reflected by the Q-Q plots of the standardized residuals. Most of the dots are above the red line that indicates equivalence, which indicates an overall bias of the residuals: in addition to <em>underestimating</em> low album sales/<em>overestimating</em> high album sales, there is an overall underestimation bias of the model:</p>
<ul>
<li>mean residuals = 0.195 for the model without intercept</li>
<li>mean residuals = 0 for the model with intercept</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="IncludingIntercept_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>In conclusion, while the model might still have favorable model metrics, the systematic error indicates that the model is <strong>miss-specified</strong> and fails to capture important characteristics of the data (namely, its mean). Consequently, the various metrics (<span class="math inline">\(b\)</span>’s, <span class="math inline">\(t\)</span>, <span class="math inline">\(F\)</span>) that are computed cannot be safely interpreted.</p>
<section id="why-does-the-model-without-intercept-still-predict-so-well" class="level3">
<h3 class="anchored" data-anchor-id="why-does-the-model-without-intercept-still-predict-so-well">Why does the model without intercept still predict so well?</h3>
<p><strong>Disclaimer:</strong> this is somewhat of a rabbit hole, so proceed with caution.</p>
<blockquote class="blockquote">
<p>The .jasp file with the analyses can be downloaded <a href="https://johnnydoorn.github.io/statistics-lectures/courses/SSR/SSR_2023-2024/MiscFiles_J/JASP_Files/Album%20Sales%20Intercept.jasp">here</a>, and the results can be previewed <a href="https://johnnydoorn.github.io/statistics-lectures/courses/SSR/SSR_2023-2024/MiscFiles_J/JASP_Files/Album%20Sales%20Intercept.html">here</a>.</p>
</blockquote>
<p>Having said that, it can still be interesting to look into <strong>why</strong> these metrics are not to be trusted. The results given by software are still based on some computation, so how can these computations miss their mark?</p>
<p>The results are fairly counter-intuitive, because the <span class="math inline">\(R^2\)</span> value is even higher for the model without intercept, than the model with intercept:</p>
<p><img src="linRegOmitIntercept.png" class="img-fluid" width="600"> <img src="linRegWithIntercept.png" class="img-fluid" width="600"></p>
<p>The proportion of explained variance has a general notation: <span class="math display">\[ R^2  = \frac{SS_M}{SS_T}. \]</span> It is the model sum of squares (i.e., squared differences between prediction and the grand mean), divided by the total sum of squares (i.e., squared difference between observation and the grand mean). If we compute this for the model with the intercept, we get the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>SS_model <span class="ot">&lt;-</span> <span class="fu">sum</span>((mainModel<span class="sc">$</span>fitted.values <span class="sc">-</span> <span class="fu">mean</span>(data<span class="sc">$</span>sales))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>SS_total <span class="ot">&lt;-</span> <span class="fu">sum</span>((data<span class="sc">$</span>sales <span class="sc">-</span> <span class="fu">mean</span>(data<span class="sc">$</span>sales))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>SS_model <span class="sc">/</span> SS_total <span class="co"># R2 for the model with intercept</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3587037</code></pre>
</div>
</div>
<p>There is about 35% explained variance by looking at airplay. What is happening implicitly here, is that we are using the predictions of the null model (i.e., the grand mean): - The model sum of squares is the difference between the alternative model and the null model predictions - The total sum of squares is the prediction error of the null model</p>
<p>When we include the intercept, the null model also includes the intercept, which allows it to predict the grand mean. This allows us to use “mean(sales)” and “predictions of the null model” interchangeably.</p>
<p>However, when we exclude the intercept, the null model does not have an intercept, and so it simply predicts <span class="math inline">\(0\)</span>. Now, the predictions of the null model are not equal to “mean(sales)” anymore, but to 0. If we want to apply the <span class="math inline">\(R^2\)</span> formula, we have to incorporate that information:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>SS_model <span class="ot">&lt;-</span> <span class="fu">sum</span>((omitInterceptModel<span class="sc">$</span>fitted.values <span class="sc">-</span> <span class="dv">0</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># difference alternative and null predictions</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>SS_total <span class="ot">&lt;-</span> <span class="fu">sum</span>((data<span class="sc">$</span>sales <span class="sc">-</span> <span class="dv">0</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># error of the null model</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>SS_model <span class="sc">/</span> SS_total <span class="co"># R2 for the model without intercept</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8779544</code></pre>
</div>
</div>
<p>We have retrieved the <span class="math inline">\(R^2\)</span> reported by JASP! It is much higher than the proportion of explained variance of the model with intercept, so why is that? Model comparison is inherently a relative endeavor: we compare one model’s predictions to another model’s predictions. When we compute an F-statistic or <span class="math inline">\(R^2\)</span> for a model, we compare it to another (e.g., null) model. When we omit the intercept, it is removed from both models. Without an intercept for the null model, the increase in predictive accuracy is much greater when adding the predictor variable, since it can explain some of the variance that is normally explained by the intercept.</p>
<p>This case underscores why assumptions matter: we might have found an alternative model (no intercept) that outperforms its null-equivalent by a greater margin than another alternative model (intercept). However, this either indicates the alternative model does fairly well, or the null model does very poorly. In the case of no intercept, the null model is predicting so poorly, that by comparison, the alternative model is awesome. Luckily, we are now equipped with various assumption testing tools that allow us to assess whether the models are miss-specified.</p>
</section>
<section id="take-aways" class="level2">
<h2 class="anchored" data-anchor-id="take-aways">Take-aways</h2>
<ul>
<li>Omitting the intercept can lead to a miss-specified model (i.e., a model with systematic bias/error).
<ul>
<li>When the model is miss-specified, inference based on its estimates becomes unreliable and we run the risk of over- or under-estimating the population parameters.</li>
<li><strong>Exercise:</strong> based on the .jasp file linked above, transform the sales variable by subtracting its mean value (<a href="https://johnnydoorn.github.io/statistics-lectures/courses/SSR/SSR_2023-2024/MiscFiles_J/JASP_Gifs/Getting-Started_CenterVariable.gif">gif</a>). Then, rerun the linear regressions (with and without intercept) - what do you observe now?</li>
</ul></li>
<li>If we omit the intercept from the alternative model, it is also omitted from the null model.
<ul>
<li>This generally leads to a larger gap between the null and alternative model, because the alternative model still has its continuous predictor to explain variance.</li>
<li>Metrics that compare the alternative to the null model (e.g., F or <span class="math inline">\(R^2\)</span>) are especially affected by omitting the intercept.</li>
</ul></li>
</ul>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>It can also be the case that such correlations between residual and prediction are 0, but there is still systematic error, such as a funnel shape (<a href="https://miro.medium.com/v2/resize:fit:1400/1*a5bBaHsYqBN1A4gYhXvD8w.png">example here</a>); this is why a scatterplot is much more informative about this assumption than only looking at a correlation value.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>