<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="JvD">
<meta name="dcterms.date" content="2023-10-11">

<title>Predicting with Dummies Part 1: Single Predictor</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="PredictingWithDummies_files/libs/clipboard/clipboard.min.js"></script>
<script src="PredictingWithDummies_files/libs/quarto-html/quarto.js"></script>
<script src="PredictingWithDummies_files/libs/quarto-html/popper.min.js"></script>
<script src="PredictingWithDummies_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PredictingWithDummies_files/libs/quarto-html/anchor.min.js"></script>
<link href="PredictingWithDummies_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PredictingWithDummies_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PredictingWithDummies_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PredictingWithDummies_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PredictingWithDummies_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="PredictingWithDummies.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting with Dummies Part 1: Single Predictor</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">JvD </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Amsterdam
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 11, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>To illustrate more clearly how we make predictions based on our statistical model, let’s get our ducks in a row. We have our <a href="https://johnnydoorn.github.io/statistics-lectures/courses/SSR/SSR_2023-2024/12.%20ANCOVA/12.%20ANCOVA.html#the-data">observed data from the lecture</a>, loaded below. The dummy representation is especially important to see the similarity between ANOVA and linear regression. When we discuss regression in block 3 we will return to this similarity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"ExtraversionNationality.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>nationality <span class="ot">&lt;-</span>  <span class="fu">factor</span>(data<span class="sc">$</span>nationality, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Dutch"</span>, <span class="st">"German"</span>, <span class="st">"Belgian"</span>)) <span class="co"># make sure nationality is a factor</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n nationality openness extraversion
1 1       Dutch     8.42        39.81
2 2       Dutch     9.38        43.85
3 3       Dutch     6.70        36.85
4 4       Dutch     8.07        39.47
5 5       Dutch     7.61        35.66
6 6       Dutch     6.14        33.78</code></pre>
</div>
</div>
<p>With observed group means:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(extraversion <span class="sc">~</span> nationality, data, mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  nationality extraversion
1       Dutch     38.67000
2      German     42.16625
3     Belgian     43.79800</code></pre>
</div>
</div>
<p>If we predict only based on nationality, we want to predict three separate values (Dutch/German/Belgian). We can write this as a regression formula with an intercept (<span class="math inline">\(b_0\)</span>) and two additional <span class="math inline">\(b\)</span>’s that indicate the group differences. The <span class="math inline">\(b_0\)</span> (the intercept) can then be set to the observed Dutch mean (<span class="math inline">\(b_0\)</span> = 38.67), and the two additional <span class="math inline">\(b\)</span>’s encode the difference between Dutch and German (<span class="math inline">\(b_1\)</span> = 42.16625 - 38.67 = 3.49625), and the difference between Dutch and Belgian (<span class="math inline">\(b_2\)</span> = 43.798 - 38.67 = 5.128). In such a way, to get the German mean, we sum <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>: 38.67 + 3.49625 = 42.16625.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>myModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(extraversion <span class="sc">~</span> nationality, <span class="at">data =</span> data)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>myModel<span class="sc">$</span>coefficients <span class="co"># prints the estimated coefficients, these are b0, b1, b2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept)  nationalityGerman nationalityBelgian 
          38.67000            3.49625            5.12800 </code></pre>
</div>
</div>
<p>To complete the regression formula, such that we select the right <span class="math inline">\(b\)</span>’s to sum, based on nationality, we can add <strong>dummy variables</strong> (also known as <strong>indicator variables</strong>). These are variables that are binary: 0 or 1, based on whether a participant belongs to certain group. For instance, we can add a dummy variable for Germans, where all Germans in the sample receive a 1, and the rest a 0:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data[[<span class="st">"germanDummy"</span>]] <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(data<span class="sc">$</span>nationality <span class="sc">==</span> <span class="st">"German"</span>, <span class="at">yes =</span> <span class="dv">1</span>, <span class="at">no =</span> <span class="dv">0</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>data[[<span class="st">"belgianDummy"</span>]] <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(data<span class="sc">$</span>nationality <span class="sc">==</span> <span class="st">"Belgian"</span>, <span class="at">yes =</span> <span class="dv">1</span>, <span class="at">no =</span> <span class="dv">0</span>) <span class="co"># and the same for the Belgians</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>With the dummies and <span class="math inline">\(b\)</span>’s defined, we have a neat regression formula that illustrates how we predict values based on group membership: <span class="math display">\[ \text{Extraversion prediction} =  b_0 + b_1 * \text{dummy}_{German} + b_2 * \text{dummy}_{Belgian}.\]</span> Writing it in this way ensures that if someone is German, we start with the Dutch mean, and then add the difference between German and Dutch means, because we add <span class="math inline">\(b_1\)</span> for Germans (since they have a 1 for <span class="math inline">\(\text{dummy}_{German}\)</span>). We do <strong>not</strong> add <span class="math inline">\(b_2\)</span> for Germans, since they score a 0 on <span class="math inline">\(\text{dummy}_{Belgian}\)</span>, and so <span class="math inline">\(b_2 * \text{dummy}_{Belgian} = 0\)</span>.</p>
<section id="adding-a-covariate" class="level3">
<h3 class="anchored" data-anchor-id="adding-a-covariate">Adding a covariate</h3>
<p>We can include a covariate in our model, although then the <span class="math inline">\(b\)</span>’s are also adjusted based on the inclusion of the covariate (and are not exactly equal to the group differences anymore). However, the logic of plugging in the relevant variables in the regression formula (<span class="math inline">\(b\)</span>’s, dummy values, and now also the covariate values) to get predictions from the model is still exactly the same. The regression formula that we fit now has an additional <span class="math inline">\(b\)</span> which indicates the association between the DV and covariate (extraversion and openness to experience): <span class="math display">\[ \text{Extraversion prediction} =  b_0 + b_1 * \text{dummy}_{German} + b_2 * \text{dummy}_{Belgian} + b_3 * \text{Openness}.\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>myModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(extraversion <span class="sc">~</span> nationality <span class="sc">+</span> openness, <span class="at">data =</span> data) <span class="co"># now added openness as predictor</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> myModel<span class="sc">$</span>coefficients <span class="co"># extract model coefficients, these are b0, b1, b2, b3</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>coefs <span class="co"># prints the estimated coefficients</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept)  nationalityGerman nationalityBelgian           openness 
         15.964661           2.769346           4.181430           2.880866 </code></pre>
</div>
</div>
<p>Note how now the intercept is no long equal to the Dutch mean, but has bedome a bit more abstract due to the addition of a covariate. To get predictions for Dutch people, we now take the intercept (<span class="math inline">\(b_0\)</span>), and add their openness score, multiplied by 2.8808659. For Dutch people, both dummy variables are equal to 0, so we do not include <span class="math inline">\(b_1\)</span> or <span class="math inline">\(b_2\)</span>. For Germans, we take the same things as for Dutch people, but then still add <span class="math inline">\(b_1\)</span> (using the similar logic as with the previous model).</p>
<p>For instance, for participant 1, we estimate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>data[<span class="dv">1</span>, ] <span class="co"># look at first row</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n nationality openness extraversion germanDummy belgianDummy
1 1       Dutch     8.42        39.81           0            0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data[<span class="dv">1</span>, <span class="st">"openness"</span>] <span class="co"># their openness score</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.42</code></pre>
</div>
</div>
<p><span class="math display">\[ \text{Extraversion prediction} =  b_0 + b_1 * 0 + b_2 * 0 + b_3 * \text{Openness}.\]</span></p>
<p>15.9646612 + * 2.8808659 = 40.2215521.</p>
<p>However, for a German with the same Openness score, we would estimate: <span class="math display">\[ \text{Extraversion prediction} =  b_0 + b_1 * 1 + b_2 * 0 + b_3 * \text{Openness}.\]</span> 15.9646612 + 2.7693458 + * 2.8808659 = 42.9908979.</p>
</section>
<section id="what-now" class="level3">
<h3 class="anchored" data-anchor-id="what-now">What now?</h3>
<p>Now that we know how to predict values based on a model, we can see how well those predictions match the observed values. This then allows us to partition the observed variance of the dependent variable into <strong>model error</strong> and <strong>model accuracy</strong>.</p>
<p>In order to get separate F-values for the two predictors, we can then further decompose the model accuracy sum of squares. We can fit different models again, look at their predictions, and obtain the sum of squares for each model’s accuracy:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>modelGroup <span class="ot">&lt;-</span> <span class="fu">lm</span>(extraversion <span class="sc">~</span> nationality, <span class="at">data =</span> data)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>modelCovar <span class="ot">&lt;-</span> <span class="fu">lm</span>(extraversion <span class="sc">~</span> openness, <span class="at">data =</span> data)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>modelFull <span class="ot">&lt;-</span> <span class="fu">lm</span>(extraversion <span class="sc">~</span> nationality <span class="sc">+</span> openness, <span class="at">data =</span> data )</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>groupPredictions <span class="ot">&lt;-</span> <span class="fu">round</span>(modelGroup<span class="sc">$</span>fitted.values, <span class="dv">2</span>) <span class="co"># predictions of the group model (simply the group means)</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>ssGroupModel <span class="ot">&lt;-</span> <span class="fu">sum</span>((groupPredictions <span class="sc">-</span> <span class="fu">mean</span>(data<span class="sc">$</span>extraversion))<span class="sc">^</span><span class="dv">2</span>) <span class="co"># model accuracy for the group model only</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>covarPredictions <span class="ot">&lt;-</span><span class="fu">round</span>(modelCovar<span class="sc">$</span>fitted.values, <span class="dv">2</span>) <span class="co"># predictions of the covariate model</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>ssCovarModel <span class="ot">&lt;-</span> <span class="fu">sum</span>((covarPredictions <span class="sc">-</span> <span class="fu">mean</span>(data<span class="sc">$</span>extraversion))<span class="sc">^</span><span class="dv">2</span>) <span class="co"># model accuracy for the covariate model only</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>fullPredictions <span class="ot">&lt;-</span> <span class="fu">round</span>(modelFull<span class="sc">$</span>fitted.values, <span class="dv">2</span>) <span class="co"># predictions of the group model (simply the means)</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>ssFullModel <span class="ot">&lt;-</span> <span class="fu">sum</span>((fullPredictions <span class="sc">-</span> <span class="fu">mean</span>(data<span class="sc">$</span>extraversion))<span class="sc">^</span><span class="dv">2</span>) <span class="co"># model accuracy for the full model</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>ssFullModelError <span class="ot">&lt;-</span> <span class="fu">sum</span>((fullPredictions <span class="sc">-</span> data<span class="sc">$</span>extraversion)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># sum squares of the error of the full model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The sums of squares of those simpler models (the one with only group <code>modelGroup</code>, and only covariate <code>modelCovar</code>), can be used to partition the model accuracy of the full model. We know that the full model accuracy is 207.514785, and that this is composed of accuracy from group, and from the covariate.</p>
<p>In order to get the full model accuracy that we can attribute to the covariate, we take the full model accuracy (207.514785), and subtract the model accuracy of the group only model (85.668455): 207.514785 - 85.668455 = 121.84633.</p>
<p>In the same way, we can get the accuracy of the full model that we can attribute to the group: 207.514785 - 152.857005 = 54.65778.</p>
<p>These are the same values we saw on the slides. To go from these sums of squares to the F-value, we first convert them to mean squares by dividing the sums of squares by the degrees of freedom of the effects. For nationality, this is equal to the number of groups - 1, so 2 in this case; for the covariate, this df equals 1.</p>
<p>To get the error mean square, we take the error sum of squares of the full model, divided by the error df (<span class="math inline">\(N - k -1 = 16\)</span>):20.1095 / 16 = 1.2568438.</p>
<p>Together, the error mean square and the mean square of each predictor can be used to obtain their F-ratio:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>errorDF <span class="ot">&lt;-</span> <span class="dv">16</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>msFullError <span class="ot">&lt;-</span> ssFullModelError <span class="sc">/</span> errorDF</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># partitioning the sum of squares of the full model, into which parts are explained by which predictor:</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># we base this on the individual models: we look at the accuracy of the group only model, and of the covariate only model</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># to divide the accuracy of the full model, we subtract the individual model accuracy from it:</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>ssGroup <span class="ot">&lt;-</span> (ssFullModel <span class="sc">-</span> ssCovarModel) <span class="co"># what is left of the full SS when we subtract the covariate accuracy?</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>ssCovar <span class="ot">&lt;-</span> (ssFullModel <span class="sc">-</span> ssGroupModel) <span class="co"># what is left of the full SS when we subtract the group accuracy?</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># converting these sum of squares to mean squares:</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>msGroup <span class="ot">&lt;-</span> ssGroup <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>msCovar <span class="ot">&lt;-</span> ssCovar <span class="sc">/</span> <span class="dv">1</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we have F-ratio's:</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>fGroup <span class="ot">&lt;-</span> msGroup <span class="sc">/</span> msFullError</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>fCovar <span class="ot">&lt;-</span> msCovar <span class="sc">/</span> msFullError</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>fGroup</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.74406</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fCovar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 96.94628</code></pre>
</div>
</div>
<p>Based on the F ratio’s we could then get p-values for hypothesis testing (or do much more fun stuff, like Bayes factors!)</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>