---
title: "6. Visualization and Correlation"
author: "Johnny van Doorn"
date: "10 sep 2025"
footer: "Scientific & Statistical Reasoning"
format:
  revealjs:
    output-ext: slide.html
    css: ../../ajohnson.css
  html: default
css: ../../ajohnson.css
---


<div class="goals">
In this lecture we aim to:

* Introduce JASP
  * Descriptive Statistics
  * Data Visualizations
* Correlation
    
<strong>Reading:</strong>
Chapters 4, 5, 7


```{r child="../../topics/JASP/JASP.qmd", eval=TRUE}
```


```{r child="../../topics/graphs/graphs.qmd", eval=TRUE}
```

```{r child="../../topics/correlation/correlation.qmd", eval=TRUE}
```

## Bored? 
::: {}
- [Exercise 1.1](https://discoverjasp.com/pages/smart_alex#task-1.1)

- [Exercise 2.2](https://discoverjasp.com/pages/smart_alex#task-2.2), [Exercise 2.6](https://discoverjasp.com/pages/smart_alex#task-2.6), [Exercise 2.7](https://discoverjasp.com/pages/smart_alex#task-2.7)   

- [Exercise 3.1](https://discoverjasp.com/pages/smart_alex#task-3.1), [Exercise 3.4](https://discoverjasp.com/pages/smart_alex#task-3.4)   

:::

<!-- Footer insert below -->

```{r child="../../footer.qmd"}
```
