---
title: "5. JASP & Visualization"
author: "Johnny van Doorn"
date: "9 September 2026"
view: "https://amsuni-my.sharepoint.com/:v:/g/personal/j_b_vandoorn_uva_nl/IQDrIfwQyyl8TZPGFsiFTp7qAZjx_earKlylnJmV_gSG5eg?e=DYoMrE&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
footer: "Scientific & Statistical Reasoning"
format:
  revealjs:
    output-ext: slide.html
    css: ../../ajohnson.css
  html: default
css: ../../ajohnson.css
---

<div class="goals">
In this lecture we aim to:

* Introduce JASP
  * Descriptive statistics
  * Data visualizations
  
<strong>Reading:</strong>
Chapters 4 (§4.1–4.10), 5 (§5.1–5.6)
</div>


```{r child="JASP.qmd", eval=TRUE}
```


```{r child="visualization.qmd", eval=TRUE}
```


# Closing

## Next Week

- Variance and z-scores
- The t-distribution
- Correlation
  - How it works
  - Controlling for a third variable

## Recommended Exercises

- [Exercise 5.1](https://discoverjasp.com/pages/smart_alex#task-5.1)

```{r child="../../footer.qmd"}
```
