# Variance and z-scores {.section}

```{r, eval=TRUE, echo=FALSE}
source("../../_setup.R")
```

## Load data

```{r, eval=TRUE, echo=TRUE}
n     <- 10
data <- read.csv(datasetsPath("Album Sales.csv"))[, -4]
data <- data[1:n, ] # take the first 10 rows of the album sales data set from Field
ssrTable(data)
```


## Variance {.subsection}

```{r, echo = FALSE}
sales         <- data$sales
airplay       <- data$airplay
mean.sales    <- mean(sales)
mean.airplay  <- mean(airplay)
N             <- length(sales)

plot(data$sales, 
     bg='orange', pch = 21, bty = "n", ylim = c(0, 420),
     ylab="Variables",las = 1,
     xlab="Album nr.")
points(data$airplay, bg='blue', pch = 21)
legend("topright", legend = c("Airplay", "Sales"), fill = c("blue", "orange"), bty = "n")
lines(rep(mean.sales, N), col='orange')
lines(rep(mean.airplay,    N), col='blue', lt=1)
```

## Standardize 

$$z = \frac{x_i - \bar{x}}{{sd}_x}$$

```{r, echo=TRUE}
z.sales      <- (data$sales   - mean(data$sales))   / sd(data$sales)
z.airplay    <- (data$airplay - mean(data$airplay)) / sd(data$airplay)
```

## Standardize {.smaller}

```{r, echo= FALSE}
mean.z.sales      <- mean(z.sales)
mean.z.airplay <- mean(z.airplay)

plot(z.sales, 
     bg  = 'orange', pch = 21, bty = "n",ylim = c(-2.5, 3.5),
     ylab = "z-scores", xlab="Album nr.")

points(z.airplay,  pch = 21, bg='blue')
legend("topright", legend = c("z-airplay", "z-sales"), fill = c("blue", "orange"), bty = "n")

# # Add mean lines
lines(rep(mean.z.sales, N), col='orange')
lines(rep(mean.z.airplay,    N), col='blue', lt=2)
# 
```

## Standardize {.smaller}

```{r, echo= FALSE}
mean.z.sales      <- mean(z.sales)
mean.z.airplay <- mean(z.airplay)

plot(z.sales, 
     bg  = 'orange', pch = 21, bty = "n",ylim = c(-2.5, 3.5),
     ylab = "z-scores", xlab="Album nr.")

points(z.airplay,  pch = 21, bg='blue')
legend("topright", legend = c("z-airplay", "z-sales"), fill = c("blue", "orange"), bty = "n")

# # Add mean lines
lines(rep(mean.z.sales, N), col='orange')
lines(rep(mean.z.airplay,    N), col='blue', lt=2)
# 
# # Add vertical variance lines
# segments(1:N, z.airplay, 1:N, z.sales, col='red')
segments(1:N, mean.z.sales, 1:N, z.sales, col='orange')
segments(1:N, mean.z.airplay, 1:N, z.airplay, col='blue', lty = 2)
```
