# project:
#   output-dir: ../slides/
author: Johnny van Doorn"
institute: "University of Amsterdam"
format:
  html:
    toc: true
    toc-depth: 2
    toc-location: left
  revealjs:
    smaller: false
    linkcolor: '#BC0031'
    logo: images/logo_uva.png
    transition: slide
    background-transition: fade
    theme: white
    slide-number: true
    css: uva_reveal.css
    touch: true
    title-slide-attributes:
      data-background-image: images/bikes.jpg
      data-background-size: contain
      data-background-position: bottom
      
# project:
#   output-dir: ../handouts/
# format:

