---
title: "SSR - Overview"
author: "Johnny van Doorn"
date: today
format:
  html:
    toc: true
    toc-location: left
---

This page will be continuously updated to feature slides and extra materials, such as applets, data sets, and additional explanations.

## Slides

```{r child="../SSR/2025/SSR.qmd"}
```


## Applets
```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
library("lubridate")
library("dplyr")
library('kableExtra')
allLinks <- c("https://statisticalreasoning-uva.shinyapps.io/NHST_Binomial",
              "https://statisticalreasoning-uva.shinyapps.io/NHST_Continuous",
              # "https://statisticalreasoning-uva.shinyapps.io/NHST_Fdistribution",
              # "https://statisticalreasoning-uva.shinyapps.io/onewayANOVA",
              # "https://statisticalreasoning-uva.shinyapps.io/ANCOVA",
              # "https://statisticalreasoning-uva-2.shinyapps.io/Multi-ANOVA",
              # "https://statisticalreasoning-uva-2.shinyapps.io/RM_ANOVA",
               "https://statisticalreasoning-uva-2.shinyapps.io/SimpleRegression"
              # "https://statisticalreasoning-uva-2.shinyapps.io/MultiRegression"

)

topics <- gsub("shinyapps.io/", "", gsub("shinyapps.io/", "", str_extract(allLinks, "shinyapps.io/(.*)")))

allLinks <- sprintf('<a href="%s" target="_blank" class="external">link</a>',allLinks) 

knitr::kable(dplyr::arrange(data.frame(Topic = topics, Link = allLinks)), escape = FALSE, format = "html"  ) %>%
  kable_styling(full_width = TRUE)
```

## Additional Explanations
```{r, echo=FALSE, warning=FALSE, message=FALSE}
files <- list.files(full.names = FALSE, pattern = "\\qmd", recursive = FALSE, path = "../extra-texts")

lectures <- data.frame()
n <- length(files)

files <- files[order(as.numeric(gsub("\\..*", "", files)))]
files <- files[files!= "OverviewSSR.qmd"]
htmlFiles <- gsub(x =files, pattern = ".qmd", replacement = ".html")
htmlFiles <- htmlFiles[htmlFiles %in% c("OneSidedVsTwoSided.html","Heteroscedasticity.html", "EffSizeVsTestStat.html", "ViolatingNormalityANOVA.html")]

allLinks <- sprintf('<a href="https://johnnydoorn.github.io/teaching-statistics/extra-texts/%s" target="_blank" class="external">link</a>',htmlFiles) 

titles <- gsub(htmlFiles, pattern = ".html", replacement = "")

linkList <- data.frame(Topic = titles, Links = allLinks)

knitr::kable(dplyr::arrange(linkList), escape = FALSE, format = "html"  ) %>%
  kable_styling(full_width = TRUE)

```

<!-- ## JASP + Data Files -->
```{r, echo=FALSE, warning=FALSE, message=FALSE, eval=FALSE}
files <- list.files(full.names = FALSE, pattern = "\\jasp", recursive = FALSE, 
                    path = "../datasets")

files <- files[order(as.numeric(gsub("\\..*", "", files)))]
files <- files[files!= "OverviewSSR.qmd"]
htmlFiles <- gsub(x =files, pattern = ".jasp", replacement = ".html")

htmlFiles <- gsub(x =files, pattern = ".jasp", replacement = ".html")
htmlFound <- list.files(full.names = FALSE, pattern = "\\html", recursive = FALSE, 
                    path = "../datasets")
csvFound  <- list.files(full.names = FALSE, pattern = "\\csv", recursive = FALSE, 
                    path = "../datasets")
  
htmlLinks <- sprintf('<a href="https://johnnydoorn.github.io/teaching-statistics/datasets/%s" target="_blank" class="external">link</a>',htmlFiles) 
htmlLinks[!(htmlFiles %in% htmlFound)] <- "-"

jaspLinks <- sprintf('<a href="https://johnnydoorn.github.io/teaching-statistics/datasets/%s" target="_blank" 
                     class="external">link</a>',files) 
titles <- gsub(htmlFiles, pattern = ".html", replacement = "")

csvFiles <- gsub(x =files, pattern = ".jasp", replacement = ".csv")
csvLinks <- sprintf('<a href="https://johnnydoorn.github.io/teaching-statistics/datasets/%s" target="_blank" class="external">link</a>',csvFiles) 
csvLinks[!(csvFiles %in% csvFound)] <- "-"


linkList <- data.frame(Topic = titles, Html = htmlLinks, JASP = jaspLinks, Csv = csvLinks)

knitr::kable(dplyr::arrange(linkList), escape = FALSE, format = "html"  ) %>%
  kable_styling(full_width = TRUE)

```


## JASP Help

The [JASP Video Library](https://jasp-stats.github.io/jasp-video-library/) offers screen-recordings that demonstrate all sorts of cool analyses and features in JASP.

<!-- ```{r child="../jasp-gifs/jasp-gifs-overview.qmd"} -->
<!-- ``` -->

