{
  "hash": "68ce5443ccfce951a54870a734e5e96a",
  "result": {
    "markdown": "---\ntitle: \"10. T-tests\"\nauthor: \"Sharon Kinkenberg & Johnny van Doorn\"\ndate: \"24 sep 2024\"\nfooter: \"Scientific & Statistical Reasoning\"\nformat:\n  revealjs:\n    output-ext: slide.html\n  html: \n    toc: true\n---\n\n\n# Block 1\n\n- General NHST concepts\n    - Sampling distribution, type I/II error, $p$-value\n- Application to $t$-test\n    - Sampling distribution\n    - Effect size\n    - In JASP\n    - Assumptions\n    \n# Today\n\n- ~~General NHST concepts~~\n    - ~~Sampling distribution, type I/II error, $p$-value~~\n- Application to $t$-test\n    - ~~Sampling distribution~~\n    - ~~Effect size~~\n    - In JASP\n    - Assumptions\n\n\n\n\n# One-sample t-test {.section}\n\n## IQ next to you\n\n::: {.r-stack}\n<img src=\"qr_9umub.png\" style=\"width:40%;\"/>\n\n<p style=\"font-size: 30px;\"> https://edu.nl/9umub</p>\n\n\n:::\n\n## Models {.center}\n\n<div style=\"font-size:200%; transform: rotate(-11deg);\">\n$$\\text{outcome} = \\text{model} + \\text{error}$$\n</div>\n\n## Compare sample mean to 120 {.smaller}\n\n<small>\nWe use the one-sample t-test to compare the sample mean $\\bar{x}$ to the population mean $\\mu = 120$. \n\nLet's take a sample and calculate the mean of this sample.\n</small>\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu     <- 120\nn      <- length(IQ.next.to.you)\nx      <- IQ.next.to.you\nmean_x <- mean(x, na.rm = TRUE)\nsd_x   <- sd(x, na.rm = TRUE)\ncbind(n, mean_x, sd_x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      n   mean_x     sd_x\n[1,] 69 116.8841 16.10219\n```\n:::\n:::\n\n<small>\nDoes this mean differ significantly from the student population mean $\\mu = 120$?\n</small>\n\n## Hypothesis {.subsection}\n\n### Null hypothesis\n\n* $H_0: \\bar{x} = \\mu$\n\n### Alternative hypothesis\n\n* $H_A: \\bar{x} \\neq \\mu$\n* $H_A: \\bar{x} > \\mu$\n* $H_A: \\bar{x} < \\mu$\n\n## Assumptions\n\n* Normal samples distribution\n* Random samples\n* Measurement level\n    * Interval\n    * Ratio\n\n## T-statistic\n\n$$T_{n-1} = \\frac{\\bar{x}-\\mu}{SE_x} = \\frac{\\bar{x}-\\mu}{s_x / \\sqrt{n}} = \\frac{116.88 - 120 }{16.1 / \\sqrt{69}}$$\n\nSo the t-statistic represents the deviation of the sample mean $\\bar{x}$ from the population mean $\\mu$, considering the sample size.\n\n::: {.cell}\n\n```{.r .cell-code}\ntStat <- (mean_x - mu) / (sd_x / sqrt(n)); tStat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.607419\n```\n:::\n:::\n\n## Type I error {.subsection}\n\nTo determine if this t-value significantly differs from the population mean we have to specify a type I error that we are willing to make.\n\n* Type I error / $\\alpha$ = .05\n\n## P-value one sided {.subsection}\n\nFinally we have to calculate our _p_-value for which we need the degrees of freedom $df = n - 1$ to determine the shape of the t-distribution.\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- n - 1; df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 68\n```\n:::\n:::\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nif(!\"visualize\" %in% installed.packages()) { install.packages(\"visualize\") }\nlibrary(\"visualize\")\n\nvisualize::visualize.t(-tStat, ifelse(df > 3, df, 10), section = \"upper\")\n```\n\n::: {.cell-output-display}\n![](10a.-t_test_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n## P-value two sided {.subsection}\n\n::: {.cell}\n\n```{.r .cell-code}\nvisualize.t(c(-tStat, tStat), ifelse(df > 3, df, 10), section = \"tails\")\n```\n\n::: {.cell-output-display}\n![](10a.-t_test_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n## Effect-size Cohen's $d$\n\n$$d = \\frac{t}{\\sqrt{n}}$$\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- tStat / sqrt(n)\n\nd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.1935105\n```\n:::\n:::\n\n## Applet\n\n\n[Link](https://statisticalreasoning-uva.shinyapps.io/NHST_Continuous/)\n\n\n# Paired-samples t-test {.section}\n\nPaired 2 samples\n\n## Paired-samples t-test\n\nIn the Paired samples t-test the deviation ($D$) for each pair is calculated and the mean of these deviations ($\\bar{D}$) is tested against the null hypothesis where $\\mu = 0$.\n\n$$t_{n-1} = \\frac{\\bar{D} - \\mu}{ {SE}_D }$$\nWhere $n$ (the number of cases) minus $1$, are the degrees of freedom $df = n - 1$ and $SE_D$ is the standard error of $D$, defined as $s_D/\\sqrt{n}$.\n\n## Hypothesis\n\n$$\\LARGE{\n  \\begin{aligned}\n  H_0 &: \\bar{D} = \\mu_D \\\\\n  H_A &: \\bar{D} \\neq \\mu_D \\\\\n  H_A &: \\bar{D} > \\mu_D \\\\\n  H_A &: \\bar{D} < \\mu_D \\\\\n  \\end{aligned}}$$\n\n## Data structure\n\nindex | k1 | k2\n------|----|--\n1     | x  | x\n2     | x  | x\n3     | x  | x\n4     | x  | x\n\nWhere $k$ is the level of the categorical predictor variable and $x$ is the value of the outcome/dependent variable.\n\n## Data example\n\nWe are going to use the IQ estimates we collected. You had to guess your neighbor's IQ and your own IQ.\n\nLet's take a look at the data.\n\n## IQ estimates\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-412ecdbd728bd00a927d\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-412ecdbd728bd00a927d\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\"],[110,120,110,108,115,162,110,108,108,130,110,103,120,130,104,119,108,108,135,145,110,130,130,120,125,120,115,125,105,117,120,142,130,115,152,100,115,100,110,100,100,143,108,130,120,113,131,122,120,105,113,137,100,110,105,141,120,130,145,120,120,118,105,120,90,125,125,110,80],[115,120,110,108,115,140,110,90,109,140,120,108,110,140,109,119,98,125,125,135,100,120,115,109,125,120,128,125,115,83,125,125,130,105,130,85,110,109,103,70,100,135,106,108,120,120,125,122,180,100,113,115,130,115,125,135,130,130,140,120,125,115,118,130,110,105,125,95,95]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>ownIQ<\\/th>\\n      <th>nextIQ<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"searching\":false,\"scrollY\":415,\"paging\":false,\"info\":false,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"ownIQ\",\"targets\":1},{\"name\":\"nextIQ\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n## Calculate $D$ {.smaller .subsection}\n\n::: {.cell}\n\n```{.r .cell-code}\ndiffScores <- IQ.next.to.you - IQ.you\n```\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-6c0741c2a17461b146f9\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-6c0741c2a17461b146f9\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\"],[110,120,110,108,115,162,110,108,108,130,110,103,120,130,104,119,108,108,135,145,110,130,130,120,125,120,115,125,105,117,120,142,130,115,152,100,115,100,110,100,100,143,108,130,120,113,131,122,120,105,113,137,100,110,105,141,120,130,145,120,120,118,105,120,90,125,125,110,80],[115,120,110,108,115,140,110,90,109,140,120,108,110,140,109,119,98,125,125,135,100,120,115,109,125,120,128,125,115,83,125,125,130,105,130,85,110,109,103,70,100,135,106,108,120,120,125,122,180,100,113,115,130,115,125,135,130,130,140,120,125,115,118,130,110,105,125,95,95],[5,0,0,0,0,-22,0,-18,1,10,10,5,-10,10,5,0,-10,17,-10,-10,-10,-10,-15,-11,0,0,13,0,10,-34,5,-17,0,-10,-22,-15,-5,9,-7,-30,0,-8,-2,-22,0,7,-6,0,60,-5,0,-22,30,5,20,-6,10,0,-5,0,5,-3,13,10,20,-20,0,-15,15]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>ownIQ<\\/th>\\n      <th>nextIQ<\\/th>\\n      <th>diffScores<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"searching\":false,\"scrollY\":315,\"paging\":false,\"info\":false,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"ownIQ\",\"targets\":1},{\"name\":\"nextIQ\",\"targets\":2},{\"name\":\"diffScores\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n## Calculate $\\bar{D}$\n\n::: {.cell}\n\n```{.r .cell-code}\ndiffScores      <- na.omit(diffScores) # get rid of all missing values\ndiffMean        <- mean(diffScores)\ndiffMean\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.231884\n```\n:::\n:::\n\nAnd we also need n.\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(diffScores)\nn\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 69\n```\n:::\n:::\n\n## Calculate t-value {.subsection}\n\n$$t_{n-1} = \\frac{\\bar{D} - \\mu}{ {SE}_D }$$\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- 0                # Define mu\n\ndiffSD <- sd(diffScores)          # Calculate standard deviation\ndiffSE <- diffSD / sqrt(n) # Calculate standard error\n\ndf   <- n - 1          # Calculate degrees of freedom\n\n# Calculate t\ntStat <- ( diffMean - mu ) / diffSE\ntStat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.7208622\n```\n:::\n:::\n\n## Test for significance {.subsection}\n\nTwo tailed\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nif(!\"visualize\" %in% installed.packages()) { install.packages(\"visualize\") }\nlibrary(\"visualize\")\n\nvisualize.t(c(-tStat,tStat), ifelse(df > 2, df, 5), section=\"tails\")\n```\n\n::: {.cell-output-display}\n![](10a.-t_test_files/figure-revealjs/unnamed-chunk-29-1.png){width=960}\n:::\n:::\n\n## Effect-size $r$  {.subsection}\n\n$$r = \\sqrt{\\frac{t^2}{t^2 + \\text{df}}}$$\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- sqrt(tStat^2/(tStat^2 + df))\nr\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.08708527\n```\n:::\n:::\n\n## Effect-size $d$ {.subsection}\n\n$$d = \\frac{t}{\\sqrt{n}}$$\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- tStat/(sqrt(n))\nd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.08678161\n```\n:::\n:::\n\n\n# Independent-samples t-test\n\nCompare 2 independent samples\n\n## Independent-samples t-test\n\nIn the independent-samples t-test the mean of both independent samples is calculated and the difference of these $(\\bar{X}_1 - \\bar{X}_2)$ means is tested against the null hypothesis where $\\mu = 0$.\n\n$$t_{n_1 + n_2 -2} = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\mu}{{SE}_p}$$\nWhere $n_1$ and $n_2$ are the number of cases in each group and $SE_p$ is the pooled standard error.\n\n## Hypothesis\n\n\\begin{aligned}\nH_0 &: t = 0 = \\mu_t \\\\\nH_A &: t \\neq 0 \\\\\nH_A &: t > 0 \\\\\nH_A &: t < 0 \\\\\n\\end{aligned}\n\n## Data structure\n\nindex | k | outcome\n------|----|--\n1     | 1 | x\n2     | 1 | x\n3     | 2 | x\n4     | 2 | x\n\nWhere $k$ is the level of the categorical predictor variable and $x$ is the value of the outcome/dependent variable.\n\n## Additional assumption\n\nSpecific for independent sample $t$-test.\n\n* Equality of variance\n    * $H_0$ : Variance $=$ equal ($p$ > .05)\n    * $H_A$ : Variance $\\neq$ equal ($p$ < .05)\n\n## Example\n\nWe are going to use the IQ estimates we collected. You had to guess the IQ of the one sitting next to you and your own IQ. But we are going to add class position to the data set. We did not register this so we are going to simulate some positions.\n\n::: {.cell}\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(23)\nclassPosition <- sample(c(\"front\", \"back\"), dim(data)[1], replace = TRUE)\n```\n:::\n\n## The data\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-c657e0a2ec314f316f8a\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c657e0a2ec314f316f8a\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\"],[\"front\",\"back\",\"back\",\"front\",\"back\",\"front\",\"front\",\"front\",\"front\",\"back\",\"back\",\"front\",\"front\",\"front\",\"front\",\"back\",\"back\",\"front\",\"back\",\"back\",\"front\",\"back\",\"front\",\"back\",\"back\",\"back\",\"front\",\"back\",\"front\",\"back\",\"front\",\"front\",\"back\",\"front\",\"back\",\"back\",\"front\",\"front\",\"front\",\"back\",\"front\",\"front\",\"back\",\"front\",\"front\",\"back\",\"back\",\"front\",\"front\",\"back\",\"front\",\"back\",\"back\",\"front\",\"front\",\"front\",\"front\",\"front\",\"front\",\"back\",\"back\",\"back\",\"front\",\"front\",\"back\",\"front\",\"front\",\"back\",\"back\"],[110,120,110,108,115,162,110,108,108,130,110,103,120,130,104,119,108,108,135,145,110,130,130,120,125,120,115,125,105,117,120,142,130,115,152,100,115,100,110,100,100,143,108,130,120,113,131,122,120,105,113,137,100,110,105,141,120,130,145,120,120,118,105,120,90,125,125,110,80]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>classPosition<\\/th>\\n      <th>ownIQ<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"searching\":false,\"scrollY\":415,\"paging\":false,\"info\":false,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":2},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"classPosition\",\"targets\":1},{\"name\":\"ownIQ\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n## Calculate means {.subsection}\n\n::: {.cell}\n\n```{.r .cell-code}\nownIQfront  <- subset(data, classPosition == \"front\",   select = ownIQ)$ownIQ\nownIQback <- subset(data, classPosition == \"back\", select = ownIQ)$ownIQ\n\nownIQfront.mean <- mean(ownIQfront, na.rm = TRUE)\nownIQback.mean <- mean(ownIQback, na.rm = TRUE)\n\nrbind(ownIQfront.mean, ownIQback.mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    [,1]\nownIQfront.mean 118.6053\nownIQback.mean  117.5161\n```\n:::\n:::\n\n## Calculate variance {.smaller .subsection}\n\n::: {.cell}\n\n```{.r .cell-code}\nownIQfront.var   <- var(ownIQfront,   na.rm = TRUE)\nownIQback.var <- var(ownIQback, na.rm = TRUE)\nprint(rbind(ownIQfront.var, ownIQback.var))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                   [,1]\nownIQfront.var 201.1643\nownIQback.var  234.7914\n```\n:::\n\n```{.r .cell-code}\nownIQfront.n   <- length(ownIQfront)\nownIQback.n <- length(ownIQback)\nn <- ownIQfront.n + ownIQback.n\nprint(rbind(ownIQfront.n, ownIQback.n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             [,1]\nownIQfront.n   38\nownIQback.n    31\n```\n:::\n:::\n\n\n## Calculate t-value {.smaller}\n\n$$t_{n_1 + n_2 -2} = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\mu}{{SE}_p}$$\n\nWhere ${SE}_p$ is the pooled standard error.\n\n$${SE}_p = \\sqrt{\\frac{S^2_p}{n_1}+\\frac{S^2_p}{n_2}}$$\n\nAnd $S^2_p$ is the pooled variance.\n\n$$S^2_p = \\frac{(n_1-1)s^2_1+(n_2-1)s^2_2}{n_1+n_2-2}$$\n\nWhere $s^2$ is the variance and $n$ the sample size.\n\n## Calculate pooled variance {.subsection}\n\n$$S^2_p = \\frac{(n_1-1)s^2_1+(n_2-1)s^2_2}{n_1+n_2-2}$$\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- ownIQfront.n + ownIQback.n - 2\npooledVar <- ( (ownIQfront.n-1)*ownIQfront.var + (ownIQback.n-1)*ownIQback.var ) / df\n\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 67\n```\n:::\n\n```{.r .cell-code}\npooledVar\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 216.2212\n```\n:::\n:::\n\n## Calculate pooled SE {.subsection}\n\n$$ {SE}_p = \\sqrt{\\frac{S^2_p}{n_1}+\\frac{S^2_p}{n_2}} $$\n\n::: {.cell}\n\n```{.r .cell-code}\nsePooled <- sqrt( ((pooledVar/ownIQfront.n) + (pooledVar/ownIQback.n)) )\nsePooled\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.558779\n```\n:::\n:::\n\n## Calculate t-value {.subsection}\n\n$$t_{n_1 + n_2 -2} = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\mu}{{SE}_p}$$\n\n::: {.cell}\n\n```{.r .cell-code}\ntStat <- ( ownIQfront.mean - ownIQback.mean ) / sePooled\n\ntStat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3060415\n```\n:::\n:::\n\n## Test for significance\n\nTwo tailed\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nif(!\"visualize\" %in% installed.packages()) { install.packages(\"visualize\") }\nlibrary(\"visualize\")\n\nif (df <= 3) df <- df + 5 # cheat to be able to build slides.. \nif (is.na(tStat)) tStat <- 1 # cheat to be able to build slides.. \nvisualize.t(c(-round(tStat, 2), round(tStat, 2)), df+1, section=\"tails\")\n```\n\n::: {.cell-output-display}\n![](10a.-t_test_files/figure-revealjs/unnamed-chunk-51-1.png){width=960}\n:::\n:::\n## Effect-size d\n\n$$r = \\frac{2t}{\\sqrt{n_1 + n_2}}$$\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- 2*tStat / sqrt(n)\n\nd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.07368613\n```\n:::\n:::\n\n## Effect-size r\n\n$$r = \\sqrt{\\frac{t^2}{t^2 + \\text{df}}}$$\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- sqrt(tStat^2/(tStat^2 + df))\n\nr\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.03736281\n```\n:::\n:::\n\n\n## But what about equal variances?!\n\nThere exist different hypothesis tests for this - the most used is Levene's test:\n\n::: {.cell}\n\n```{.r .cell-code}\nif(!\"car\" %in% installed.packages()) { install.packages(\"car\") }\nlibrary(\"car\")\n\nleveneTest(y = ownIQ, group = classPosition)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  1  0.0669 0.7966\n      67               \n```\n:::\n:::\n\n## But what about equal variances?!\n\n::: {.callout-warning}\nLevene's test (and other significance tests like it, such as Shapiro for normality) are heavily influenced by sample size, so a significant test result does not necessarily mean that you have a problem. A more pragmatic rule of thumb is to look at the ratio of variances - a ratio greater than 2 is problematic. Additionally, Welch test is a version of the $t$-test that handles unequal variances better. \n:::\n\n## The difference only matters when $n_A \\neq n_B$!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeanA <- 50\nmeanB <- 55\n\nsdA <- 5\nsdB <- 10\n\nnA <- 20\nnB <- 20\n\nseA <- sdA / sqrt(nA)    \nseB <- sdB / sqrt(nB)  \ntStatWelch <- (meanA - meanB) / sqrt((sdA^2 / nA) + (sdB^2 / nB))\n\n\npooledS <- sqrt(((nA - 1) * sdA^2 + (nA - 1) * sdB^2) / (nA + nB - 2))\ntStatStudent <- (meanA - meanB) / (pooledS *  sqrt(1/nA + 1/nA))\n\ntStatStudent\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -2\n```\n:::\n\n```{.r .cell-code}\ntStatWelch\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -2\n```\n:::\n:::\n\n\n## Normality?!\n\n- Test using hypothesis test (Shapiro-Wilk)\n    - $p < \\alpha \\rightarrow$ assumption violated \n    - Same caution as Levene's test (see also Jane Superbrain Box 6.7)\n    - Plus caution as with any p-value (black-and-white decision making)\n- Assess using a plot (Q-Q plot)\n    - Points should be along the diagonal\n    - Not exact \n\n    \n<img src=\"https://upload.wikimedia.org/wikipedia/en/3/3f/Pok%C3%A9mon_Snorlax_art.png\" alt=\"Snorlax\" width=\"100\"/>\n\n## Handling Assumption violations\n::: {.callout-warning}\nAssumption violations affect the shape of the sampling distribution and mess up the type 1/2 error rates\n:::\n\n- Unequal variances?\n    - Welch $t$-test\n- Non-normality?\n    - Use nonparametric test (Chapter 15/Lecture 17)\n\n\n\n# End\n\n## Contact\n\n<script src=\"https://use.fontawesome.com/23c1d38eea.js\"></script>\n\n<ul class=\"fa-ul\" style=\"color:black; list-style:none;\">\n<li><i class=\"fa-li fa fa-envelope-o\"></i> <a style=\"unicode-bidi:bidi-override; direction: rtl; color:black\" href=\"javascript:window.location.href = 'mailto:' + ['j.b.vandoorn','uva.nl'].join('@')\">ln.AvU@nrooDnav.B.J</a></li>\n<li><i class=\"fa-li fa fa-github\"></i> <a href=\"https://github.com/JohnnyDoorn\" target=\"_blank\" style=\"color:black; border-bottom:none;\">JohnnyDoorn</a></li>\n</ul>\n\n<small style=\"text-align:left;\">\n\n\n[![CC BY-NC-SA 4.0][cc-by-nc-sa-image]][cc-by-nc-sa]\n\n[cc-by-nc-sa]: http://creativecommons.org/licenses/by-nc-sa/4.0/\n[cc-by-nc-sa-image]: https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png\n[cc-by-nc-sa-shield]: https://img.shields.io/badge/License-CC%20BY--NC--SA%204.0-lightgrey.svg\n\n</small>\n",
    "supporting": [
      "10a.-t_test_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"10a. t_test_files/libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"10a. t_test_files/libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"10a. t_test_files/libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"10a. t_test_files/libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"10a. t_test_files/libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"10a. t_test_files/libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"10a. t_test_files/libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"10a. t_test_files/libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"10a. t_test_files/libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"10a. t_test_files/libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}