# Standard Error and<br>Confidence Intervals {.section}

A sample mean is not the population mean. How far off is it, typically?

## Standard Error

> 95% confidence interval

$$SE = \frac{\text{Standard deviation}}{\text{Square root of sample size}} = \frac{s}{\sqrt{n}}$$

-   Lowerbound = $\bar{x} - 1.96 \times SE$
-   Upperbound = $\bar{x} + 1.96 \times SE$

## Standard Error {.flexbox .vcenter}

```{r, child="../../images/ci.html"}
```

##

```{r, echo=FALSE, out.height=600}
set.seed(1548)

x  = seq(-4,4,.05) # sequence x values for normal distribution
hx = dnorm(x)      # calculate y values

title = expression(atop("SAMPLES FROM NORMAL DISTRIBUTION",paste(mu," falls within the CI in ~95% of the samples")))

plot(x,hx+1,type="l",ylim=c(0,1.45),xlim=c(-4,9), yaxt="n", xaxt="n",ylab="",xlab="",main=title, mai=c(3,1,2,1),mar=c(3,1,2,1))

# Add red area
polygon(c(x,rev(x)),c(rep(1,length(x)),hx+1),col="red",lty=1)

# Add mu line
lines(c(0,0),c(0,max(hx)+1))

# Add mu symbol to x axis
axis( 1,at=0,labels=expression(mu), cex=2 )

# Create curly braces for normal distribution 
ybracket = seq(1,max(hx)+1,length=39)
xbracket = rep(4.1,39)*c(c(1,1.02),rep(1.03,16),c(1.04,1.05,1.04),rep(1.03,16),c(1.02,1))

lines(xbracket,ybracket,col="black")

# Create curly braces for samples
ybracket = seq(0,1,length=39)
xbracket = rep(4.1,39)*c(c(1,1.02),rep(1.03,16),c(1.04,1.05,1.04),rep(1.03,16),c(1.02,1))

lines(xbracket,ybracket,col="black")

text = expression(atop("Normally distributed","population"))

text(4.1*1.06,1+(max(hx)/2), text,pos=4)

text = expression(atop("95% Confidence interval","in 100 samples","drawn from the","normal distribution"))

text(4.1*1.06,.5, text,pos=4)

# Add confidence intervals

mu  = 0
sig = 1

mu_in_ci = array() # create empty array

iterations = 100

for(i in 1:iterations) {
  
  n      = round(runif(1,10,60)) # use variable sample sizes between 10 and 60
  sample = rnorm(n,mu,sig)       # sample from normal distribution
  
  sample_mean = mean(sample)
  sample_sd   = sd(sample)
  sample_ci   = sample_sd/sqrt(n)
  
  sample_ci_upperbound = sample_mean + sample_ci * 1.96
  sample_ci_lowerbound = sample_mean - sample_ci * 1.96
  
  if(sample_ci_lowerbound < mu & sample_ci_upperbound > mu) {
    
    mu_in_ci[i] = 1	
    col = "darkgrey"	
  }
  else {
    mu_in_ci[i] = 0
    col = "red"
  }
  
  # plot CI lines
  lines(c(sample_ci_lowerbound,sample_ci_upperbound),rep((.98/iterations)*i,2),col=col)
  
}

percentage = (1/iterations)*sum(mu_in_ci)
```

